import assert from 'node:assert/strict';
import {supportingFileChecks,savedLoadLogbooks} from '../../source/src/modules/owneros/loadHistoryV110449.js';
import {ensureHistoricalLogbookSnapshotV10981,openAllHistoricalLogbooksPdfV10981,buildCurrentMilesPdfV1103} from '../../source/src/modules/owneros/historicalLogbookV10981.js';
const storage=new Map(),localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value)};
globalThis.localStorage=localStorage;globalThis.window={localStorage,open(){throw Error('Unexpected empty PDF window');}};
const folder={loadNo:'95916',days:['2026-05-31','2026-06-01','2026-06-02','2026-06-03']};
const state={eventsByDay:{'2026-09-30':[{id:'later',status:'ON',startMin:20,endMin:40}]},signatureByDay:{},homeTerminalTimeZone:'America/Chicago'};
const before=JSON.stringify(state);
assert.throws(()=>ensureHistoricalLogbookSnapshotV10981({state,folder,day:folder.days[0]}),/No recorded logbook/);
assert.throws(()=>openAllHistoricalLogbooksPdfV10981({state,folder}),/No recorded logbook/);
assert.throws(()=>buildCurrentMilesPdfV1103({state,folder}),/No recorded mileage/);
assert.equal(storage.size,0);assert.equal(JSON.stringify(state),before);
const day=folder.days[0],recorded={...state,eventsByDay:{[day]:[{id:'d',status:'D',startMin:500,endMin:560,loadNo:'95916',manualMiles:42}]},manualMilesByDay:{[day]:42}};
assert.equal(ensureHistoricalLogbookSnapshotV10981({state:recorded,folder,day}).totals.D,60);
assert.match(await buildCurrentMilesPdfV1103({state:recorded,folder}).text(),/42/);
const doc={id:'file1',original_file_name:'Trailer-return-photo.jpg'},rows=[{id:'date',document:doc,label:'Document date needs review',detail:'Check the source date.',status:'review'},{id:'facts',document:doc,label:'Source details need review',detail:'Check source details.',status:'review'}];
const grouped=supportingFileChecks(rows);assert.equal(grouped.length,1);assert.equal(grouped[0].label,doc.original_file_name);assert.equal(grouped[0].checks.length,2);assert.match(grouped[0].detail,/source date/);assert.match(grouped[0].detail,/source details/);assert.equal(grouped[0].document,doc);
assert.equal(supportingFileChecks([...rows,{...rows[0],id:'other',document:{...doc,id:'file2'}}]).length,2);
const archive={logbookLinks:[{loadNo:'95916',driverId:'beta',day,basis:'exact_reference'},{loadNo:'other',driverId:'alpha',day}],logbook:[{driverId:'beta',day,driverName:'Beta Driver',events:[{status:'ON',startMin:20,endMin:40}]},{driverId:'alpha',day,events:[{status:'D'}]}]};
assert.equal(savedLoadLogbooks([archive],'95916')[0].log.driverName,'Beta Driver');
assert.equal(savedLoadLogbooks([archive,archive],'95916').length,1);
assert.equal(savedLoadLogbooks([{...archive,logbook:archive.logbook.map(row=>({...row,events:[]}))}],'95916').length,0);
console.log('PASS: no empty logbook/mileage PDFs or snapshots; real hours/miles retained; checks grouped by original; saved source drivers remain separate');
