import assert from 'node:assert/strict';
import {recordsFrom,bundleFrom,mergeRecords,hasData,canonical} from './accountCore.js';
const book={eventsByDay:{'2026-10-04':[{id:'a',status:'ON',startMin:10,endMin:20}]},signatureByDay:{'2026-10-04':{signed:true,signatureDataUrl:'data:image/png;base64,YQ=='}},certifyStatus:{'2026-10-04':'Certified'},dailyLogs:[]};
const source={state:{...book,teamDrivers:[{id:'a',name:'Arben'},{id:'f',name:'Feriz'}],activeDriverId:'a',teamLogbooksByDriverId:{f:{eventsByDay:{'2026-10-04':[{id:'f1',status:'D'}]}}},driverProfile:{name:'Arben',email:'synthetic@example.test'},view:'logs',sheet:{x:1},gpsTrip:{device:'phone'}},business:{loads:[{id:'load1',loadNo:'123'}],documents:[]},tables:{documents_local:[{local_id:'d1',type:'bol'}]},locals:{'owner-op-road-ready-operator-profile-v1':{setupComplete:true}}};
const records=recordsFrom(source),round=bundleFrom(records,{activeDriverId:'f'});
assert.deepEqual(round.state.eventsByDay,source.state.teamLogbooksByDriverId.f.eventsByDay);
assert.deepEqual(round.state.teamLogbooksByDriverId.a.signatureByDay,book.signatureByDay);
assert.deepEqual(round.state.teamLogbooksByDriverId.a.dailyLogs,[]);
assert.equal(round.state.driverProfile.name,'Feriz');assert.equal(round.state.gpsTrip,undefined);assert.equal(round.state.sheet,null);
assert.deepEqual(round.business.loads,source.business.loads);assert.deepEqual(round.tables.documents_local,source.tables.documents_local);
const dayKey=Object.keys(records).find(k=>k.includes('day')&&k.includes('"a"'));
const phone={...records,[dayKey]:{...records[dayKey],eventsByDay:[{id:'edited',status:'D'}]}},tablet={...records,[dayKey]:{...records[dayKey],signatureByDay:{signed:false}}};
assert.equal(mergeRecords(records,phone,tablet).conflicts.length,1,'Events and their signatures must conflict together');
const k1='["business","loads","one"]',k2='["business","loads","two"]';
assert.deepEqual(mergeRecords(records,{...records,[k1]:{id:'one'}},{...records,[k2]:{id:'two'}}).conflicts,[]);
const deleted={...records};delete deleted[dayKey];assert.ok(!(dayKey in mergeRecords(records,records,deleted).records));assert.equal(mergeRecords(records,phone,deleted).conflicts.length,1);
assert.equal(hasData({}),false);assert.equal(hasData(source),true);
const dup={...source,business:{loads:[{id:'same',gross:1},{id:'same',gross:2}]}};assert.deepEqual(bundleFrom(recordsFrom(dup)).business.loads,dup.business.loads);
assert.equal(canonical(mergeRecords(records,records,records).records),canonical(records));
console.log('PASS account merge: driver separation, signed-day conflicts, disjoint offline changes, deletes, duplicates, navigation isolation');
