import assert from 'node:assert/strict';
import {formCoDriverNames,formTeamDriverSummary,registerFormTeamDrivers} from '../../source/src/core/team/formTeamV110448.js';
import {normalizeTeamDriverState,switchTeamDriver} from '../../source/src/core/team/teamLogbook.js';
import {readLogbookDayState,applyDayFormEdit} from '../../source/src/modules/logbook/dayFormV110.js';
const day='2026-10-04',old='2026-10-03';
const state=normalizeTeamDriverState({activeDay:day,activeDriverId:'alpha',driverProfile:{name:'Alpha Driver'},teamDrivers:[{id:'alpha',name:'Alpha Driver'},{id:'beta',name:'Beta Driver'},{id:'gamma',name:'Archived Driver'}],eventsByDay:{[day]:[{id:'rest',status:'SB'}]},signatureByDay:{},formByDay:{[day]:{coDrivers:'Beta Driver'},[old]:{coDrivers:'Archived Driver'}},teamLogbooksByDriverId:{beta:{activeDay:day,eventsByDay:{[day]:[{id:'pickup',status:'ON',startMin:50,endMin:80}]},signatureByDay:{[old]:{signed:true,data:'original'}}}}});
const summary=s=>formTeamDriverSummary(readLogbookDayState(s,s.activeDay));
const edit=(s,value)=>registerFormTeamDrivers(applyDayFormEdit(s,{...s,coDrivers:value},{coDrivers:value},day),value,day);
assert.deepEqual(summary(state).drivers.map(d=>d.id),['alpha','beta']);
const removed=edit(state,'');
assert.deepEqual(summary(removed).drivers.map(d=>d.id),['alpha']);
assert.deepEqual(summary(normalizeTeamDriverState(JSON.parse(JSON.stringify(removed)))).drivers.map(d=>d.id),['alpha']);
assert.deepEqual(removed.teamLogbooksByDriverId,state.teamLogbooksByDriverId);
assert.deepEqual(summary({...removed,activeDay:old}).drivers.map(d=>d.id),['alpha','gamma']);
const readded=edit(removed,' beta driver ');
assert.deepEqual(summary(readded).drivers.map(d=>d.id),['alpha','beta']);
assert.equal(readded.teamDrivers.length,3);
assert.deepEqual(readded.teamLogbooksByDriverId,state.teamLogbooksByDriverId);
const switched=switchTeamDriver(readded,'beta',day);
assert.deepEqual(switched.eventsByDay,state.teamLogbooksByDriverId.beta.eventsByDay);
assert.deepEqual(switched.signatureByDay,state.teamLogbooksByDriverId.beta.signatureByDay);
const added=edit(removed,'New Driver');
assert.equal(added.teamDrivers.length,4);
assert.deepEqual(summary(added).drivers.map(d=>d.name),['Alpha Driver','New Driver']);
assert.deepEqual(added.eventsByDay,state.eventsByDay);
assert.deepEqual(added.teamLogbooksByDriverId.beta,state.teamLogbooksByDriverId.beta);
assert.deepEqual(formCoDriverNames('Last, First',[{name:'Last, First'}]),['Last, First']);
assert.deepEqual(formCoDriverNames('Last, First, Beta Driver',[{name:'Last, First'},{name:'Beta Driver'}]),['Last, First','Beta Driver']);
assert.deepEqual(formCoDriverNames('New Person; Other Person'),['New Person','Other Person']);
assert.deepEqual(summary({...state,formByDay:{},signatureByDay:{[day]:{certificationContext:{form:{coDrivers:''}}}}}).drivers.map(d=>d.id),['alpha']);
console.log('PASS: Form removal/reload, selected-day membership, re-add reuses driver ID/logbook, new driver, frozen Form, full names');
