import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {chromium,webkit} from 'playwright';
import {baseState,seed,setupRoutes,simplePdf,origin} from './browserFixture.mjs';
import {ChunkedZip,inspectBlob} from '../../source/src/modules/backup/chunkedZipV110431.js';
import {FORMAT} from './libraryCore.js';
const out='browser-test-results/load-library-v110434';fs.mkdirSync(out,{recursive:true});
const bytes=simplePdf('Synthetic POD\nBroker load 00123'),other=simplePdf('Synthetic DOT report');
function record(data,name,type){const hash=createHash('sha256').update(data).digest('hex');return {id:'library-'+hash,sha256:hash,path:'Originals/'+name,name,bytes:data.length,mime:'application/pdf',loadNo:'00123',type,date:'2026-09-28',sourceClientIds:name==='pod.pdf'?['existing-client']:[],components:[]};}
const docs=[record(bytes,'pod.pdf','pod'),record(other,'dot.pdf','inspection')];
const p={format:FORMAT,version:1,id:'synthetic-library-one',coverageNote:'Synthetic sources only.',loads:[{loadNo:'00123',broker:'Example Broker',origin:'A, IL',destination:'B, OH',gross:1200,documentTransferDays:['2026-09-28'],operationalStatus:'closed',serviceOutcome:'completed_per_owner',documentWorkflowStage:'delivered',closureAuthority:'Owner confirmed completed',aliases:['BOL-55']}],documents:docs,logbook:[{day:'2026-09-28',driverId:'driver-a',driverName:'Example A',events:[{status:'D',startMin:0,endMin:100,location:'Example, IL',note:'Driving'}]},{day:'2026-09-28',driverId:'driver-b',driverName:'Example B',events:[{status:'SB',startMin:0,endMin:100,location:'Example, IL',note:'Sleeper'}]}],logbookLinks:[{loadNo:'00123',day:'2026-09-28',driverId:'driver-a',basis:'exact_reference'},{loadNo:'00123',day:'2026-09-28',driverId:'driver-b',basis:'source_date_review'}],cases:[{id:'TEST-DOT',title:'DOT & Repairs · TEST-DOT',date:'2026-09-28',equipment:'Truck TEST',loadNo:'00123',documentIds:[docs[1].id],note:'Synthetic case.'}]};
async function archive(manifest=p){const z=new ChunkedZip();for(const [i,d]of docs.entries()){const b=new Blob([i?other:bytes]);z.add(d.path,b,await inspectBlob(b));}await z.text('RoadReady-Import.json',JSON.stringify(manifest));return Buffer.from(await z.file('synthetic-library.zip').arrayBuffer());}
const payload=await archive();
const recoveryPressure=process.env.LIBRARY_STORAGE_PRESSURE==='recovery';
async function stored(page){return page.evaluate(async()=>{const business=JSON.parse(localStorage.getItem('owner-op-road-ready-business-v1')||'{}');return new Promise((ok,no)=>{const q=indexedDB.open('owner-op-road-ready-offline-v1');q.onerror=()=>no(q.error);q.onsuccess=()=>{const db=q.result,tx=db.transaction(['documents_local','document_blobs','sync_meta','app_snapshots'],'readonly'),result={business};let count=4;for(const table of ['documents_local','document_blobs','sync_meta','app_snapshots']){const r=tx.objectStore(table).getAll();r.onsuccess=()=>{result[table]=r.result;if(!--count){db.close();ok(result);}};}};});});}
async function select(page,data=payload){await page.getByLabel('Choose load library ZIP',{exact:true}).setInputFiles({name:'library.zip',mimeType:'application/zip',buffer:data});}
for(const [name,engine]of [['chromium',chromium],['webkit',webkit]]){
 if(process.env.LIBRARY_TEST_BROWSER&&process.env.LIBRARY_TEST_BROWSER!==name)continue;
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'rr-library-test-'));const context=await engine.launchPersistentContext(profile,{headless:true,viewport:{width:390,height:1000},serviceWorkers:'block'});await setupRoutes(context);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 const state=baseState();state.view='logbook';state.testInstructionStore={loads:[{id:'stable',loadNo:'00123',broker:'Different Saved Broker',gross:500,status:'paid',paidAmount:500}],documents:[],fuel:[],expenses:[],maintenance:[],settlements:[]};
 await seed(page,state,[{id:'existing',bytes:[...bytes]}]);await page.evaluate(async(recoveryPressure)=>{
  const payload=recoveryPressure?'small OCR':'saved OCR '.repeat(190000),key='owner-op-road-ready-business-v1';
  await new Promise((ok,no)=>{const q=indexedDB.open('owner-op-road-ready-offline-v1');q.onerror=()=>no(q.error);q.onsuccess=()=>{const db=q.result,tx=db.transaction('documents_local','readwrite'),store=tx.objectStore('documents_local'),r=store.get('existing-local');r.onsuccess=()=>{store.put({...r.result,extracted:{...r.result.extracted,rawText:payload}});};tx.oncomplete=()=>{db.close();ok();};tx.onerror=()=>no(tx.error);};});
  const business=JSON.parse(localStorage.getItem(key));business.documents=[{id:'existing-local',localDocumentId:'existing-local',clientDocumentId:'existing-client',type:'other',loadNo:'82002',extracted:{rawText:payload,bolNo:'BOL-55'},privateLegacyNote:'Keep this exact original business metadata'}];localStorage.setItem(key,JSON.stringify(business));
  let low=0,high=6*1024*1024;while(high-low>1024){const mid=Math.floor((low+high)/2);try{localStorage.setItem(recoveryPressure?'owner-op-road-ready-pre-update-snapshot-v1':'synthetic-storage-pressure',recoveryPressure?JSON.stringify({_backupMeta:{kind:'pre_update'},savedRecoveryNotes:'x'.repeat(mid)}):'x'.repeat(mid));low=mid;}catch(e){if(e.name!=='QuotaExceededError')throw e;high=mid;}}
  let full=false;try{localStorage.setItem('synthetic-quota-probe','x'.repeat(16384));}catch(e){if(e.name!=='QuotaExceededError')throw e;full=true;}if(!full)throw Error('Test did not reach native localStorage quota');
 },recoveryPressure);await page.getByRole('button',{name:/^Documents/}).first().click();await page.locator('.rr-docs-browser').waitFor();await page.getByRole('button',{name:'Import documents',exact:true}).click();
 const recoveryBefore=await page.evaluate(()=>localStorage.getItem('owner-op-road-ready-pre-update-snapshot-v1'));
 const before=await stored(page);const stateBefore=before.app_snapshots.find(r=>r.key==='owner-op-road-ready-state-v1').state;
 await select(page);await page.getByLabel('Preview load import',{exact:true}).waitFor({timeout:30000});await page.getByLabel('Use the imported details shown above').check();assert.equal(await page.getByRole('button',{name:'Import folders & files',exact:true}).isDisabled(),true);await page.getByLabel('Same load 00123 — use broker Example Broker from the ZIP',{exact:true}).check();
 if(recoveryPressure){
  await page.evaluate(()=>{window.originalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,...args){if(this.name==='sync_meta'&&String(value?.key).startsWith('library-storage-recovery:'))throw new DOMException('Synthetic recovery database full','QuotaExceededError');return window.originalPut.call(this,value,...args);};});
  await page.getByRole('button',{name:'Import folders & files',exact:true}).click();await page.getByRole('alert').filter({hasText:/Synthetic recovery database full/}).waitFor();
  assert.equal(await page.evaluate(()=>localStorage.getItem('owner-op-road-ready-pre-update-snapshot-v1')),recoveryBefore);assert.deepEqual((await stored(page)).business,before.business);
  await page.evaluate(()=>{IDBObjectStore.prototype.put=window.originalPut;});
 }
 await page.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='owner-op-road-ready-business-v1')throw new DOMException('Synthetic full device','QuotaExceededError');return window.originalSetItem.call(this,k,v);};});
 await page.getByRole('button',{name:'Import folders & files',exact:true}).click();await page.getByRole('alert').filter({hasText:/document list could not fit/}).waitFor();let data=await stored(page);assert.equal(data.documents_local.length,before.documents_local.length);assert.equal(data.document_blobs.length,before.document_blobs.length);assert.deepEqual(data.business,before.business);
 if(recoveryPressure){assert.ok(data.sync_meta.some(r=>r.key.startsWith('library-storage-recovery:')&&r.value.raw===recoveryBefore));assert.equal(await page.evaluate(()=>localStorage.getItem('owner-op-road-ready-pre-update-snapshot-v1')),null);}
 await page.evaluate(({recoveryPressure,recoveryBefore})=>{Storage.prototype.setItem=window.originalSetItem;if(recoveryPressure)localStorage.setItem('owner-op-road-ready-pre-update-snapshot-v1',recoveryBefore);},{recoveryPressure,recoveryBefore});await select(page);await page.getByLabel('Preview load import',{exact:true}).waitFor();await page.getByLabel('Use the imported details shown above').check();assert.equal(await page.getByRole('button',{name:'Import folders & files',exact:true}).isDisabled(),true);await page.getByLabel('Same load 00123 — use broker Example Broker from the ZIP',{exact:true}).check();await page.getByRole('button',{name:'Import folders & files',exact:true}).click();await page.getByRole('status').filter({hasText:'Saved on this device:'}).waitFor();
 data=await stored(page);assert.equal(data.documents_local.find(d=>d.client_document_id==='existing-client').extracted.rawText,recoveryPressure?'small OCR':'saved OCR '.repeat(190000));assert.equal(data.documents_local.find(d=>d.client_document_id==='existing-client').libraryBusinessMetadataV110437.privateLegacyNote,'Keep this exact original business metadata');assert.equal(data.business.documents.find(d=>d.clientDocumentId==='existing-client').extracted.rawText,undefined);if(!recoveryPressure)assert.ok(JSON.stringify(data.business).length<JSON.stringify(before.business).length/10);else{assert.equal(await page.evaluate(()=>localStorage.getItem('owner-op-road-ready-pre-update-snapshot-v1')),null);assert.ok(data.sync_meta.some(r=>r.key.startsWith('library-storage-recovery:')&&r.value.raw===recoveryBefore));}assert.equal(data.documents_local.length,2);assert.equal(data.document_blobs.length,2);assert.equal(data.business.loads.find(l=>l.loadNo==='00123').broker,'Example Broker');assert.equal(data.sync_meta.find(r=>r.key==='document-library:'+p.id).value.audit.brokerConfirmations[0].savedBroker,'Different Saved Broker');assert.equal(data.business.loads.find(l=>l.loadNo==='00123').status,'paid');assert.equal(data.business.loads.find(l=>l.loadNo==='00123').paidAmount,500);assert.equal(data.business.loads.find(l=>l.loadNo==='00123').operationalStatus,'closed');assert.equal(data.documents_local.find(d=>d.client_document_id==='existing-client').load_no,'00123');
 for(const k of ['eventsByDay','signatureByDay','certifyStatus','formByDay'])assert.deepEqual(data.app_snapshots.find(r=>r.key==='owner-op-road-ready-state-v1').state[k],stateBefore[k]);
 await page.evaluate(()=>{const key='owner-op-road-ready-business-v1',business=JSON.parse(localStorage.getItem(key));const doc=business.documents.find(d=>d.clientDocumentId==='existing-client');doc.extracted.rawText='Historical full OCR';doc.title='Owner corrected title';localStorage.setItem(key,JSON.stringify(business));});
 const historicalRows=data.documents_local;
 await page.reload();await page.getByRole('button',{name:/^Documents/}).first().click();await page.getByRole('button',{name:'Import documents',exact:true}).click();await select(page);await page.getByLabel('Preview load import',{exact:true}).waitFor();await page.getByRole('button',{name:'Check saved originals',exact:true}).click();await page.getByRole('status').filter({hasText:'Already imported.'}).waitFor();data=await stored(page);assert.equal(data.documents_local.length,2);assert.equal(data.document_blobs.length,2);assert.deepEqual(data.documents_local,historicalRows);assert.equal(data.business.documents.find(d=>d.clientDocumentId==='existing-client').extracted.rawText,undefined);assert.equal(data.business.documents.find(d=>d.clientDocumentId==='existing-client').title,'Owner corrected title');assert.ok(data.sync_meta.some(r=>r.key.startsWith('document-library-index:')&&r.value.extracted.rawText==='Historical full OCR'));
 await page.locator('.rr-docs-card').filter({hasText:'Sep 28'}).click();await page.locator('.rr-docs-card').filter({hasText:'Load 00123'}).click();await page.getByText('Logbook · 2 saved driver days',{exact:true}).click();await page.getByRole('button',{name:/2026-09-28 · Example A/}).click();await page.getByLabel('Saved logbook source',{exact:true}).waitFor();assert.equal(await page.getByLabel('Saved logbook source',{exact:true}).locator('tbody tr').count(),1);
 await page.screenshot({path:out+'/'+name+'-linked-load.png',fullPage:true});for(const width of [320,390,820]){await page.setViewportSize({width,height:1000});assert.ok(await page.locator('.rr-docs-browser').evaluate(el=>el.getBoundingClientRect().right<=innerWidth+1));}
 assert.deepEqual(errors,[]);console.log('PASS '+name+(recoveryPressure?' recovery-copy pressure':' document pressure')+' — broker-conflict preview, per-load confirmation, original dedup, near-full real localStorage import, full metadata preservation, quota rollback, closed folders, preserved paid flags and duty evidence, reload, repeat import, two-driver logbook links, 320/390/820px');}catch(e){console.error({browser:name,errors,body:await page.locator('body').innerText()});await page.screenshot({path:out+'/'+name+'-failure.png',fullPage:true});throw e;}finally{await context.close();fs.rmSync(profile,{recursive:true,force:true});}
}
