import assert from 'node:assert/strict';
import {retainedLibraryReview} from './libraryReview.js';
import {loadView,loadReviewRows} from '../../source/src/modules/owneros/driverDocumentsV110415.js';
import {buildEvidence} from '../../source/src/modules/owneros/evidenceCoreV110413.js';
import {validateRecoveryPlan} from '../../source/src/modules/owneros/recoveryCoreV110413.js';
const hash='a'.repeat(64),load={loadNo:'L100',broker:'Test Broker',origin:'A',destination:'B',pickupDate:'2026-09-01',deliveryDate:'2026-09-03',documentWorkflowStage:'delivered'};
const fields={loadNo:'L100',date:'2026-09-01',merchant:'Test Broker',reference:'BOL-200',origin:'A',destination:'B',pickupDate:'2026-09-01',deliveryDate:'2026-09-03',total:1000,currency:'USD',podSigned:true};
const components=['invoice','rate_confirmation','pod'].map((kind,i)=>({kind,reviewed:true,pages:[i+1],fields:{...fields}}));
delete components[2].fields.deliveryDate;
const doc={client_document_id:'packet',type:'supporting_packet',load_no:'L100',sha256:hash,extracted:{evidenceFactsV1:{version:1,source:'source_recovery',sourceSha256:hash,reviewedAt:'2026-10-04',fields,components}}};
const extra={client_document_id:'extra',type:'other',load_no:'L100',sha256:'b'.repeat(64),extracted:{}};
let view=loadView(load,[doc,extra],{loads:[load]},'2026-10-04');
assert.equal(view.status.label,'Ready');assert.equal(view.attention,0);assert.equal(view.supporting.length,2);assert.match(view.service,/Sep 3/);assert.ok(!view.service.includes('Sep 1'));
const model=buildEvidence({documents:[doc,extra],loads:[load],businessStore:{loads:[load]},loadNo:'L100'});
assert.equal(loadReviewRows(model,load,{loads:[load]}).length,2,'supporting checks stay accessible');
const partial=structuredClone(doc);partial.extracted.evidenceFactsV1.components[2].reviewed=false;
view=loadView(load,[partial,extra],{loads:[load]},'2026-10-04');assert.ok(view.attention>0);assert.notEqual(view.status.label,'Ready');assert.ok(view.rows.find(r=>r.kind==='pod').status==='review');
const conflict=structuredClone(doc);conflict.client_document_id='conflict';conflict.extracted.evidenceFactsV1.fields.total=2000;view=loadView(load,[conflict,doc],{loads:[load]},'2026-10-04');assert.ok(view.review>0,'filing conflicts still block Ready');
view=loadView(load,[],{loads:[load]},'2026-10-04');assert.equal(view.missing,4);
const incoming={sha256:hash,loadNo:'L100',type:'supporting_packet',date:''};assert.deepEqual(retainedLibraryReview(doc,incoming),doc.extracted.evidenceFactsV1);
assert.deepEqual(retainedLibraryReview({...doc,contentHash:hash.toUpperCase()},incoming),doc.extracted.evidenceFactsV1,'a legacy uppercase checksum is the same original');
for(const change of [{sha256:'b'.repeat(64)},{loadNo:'OTHER'},{type:'pod'},{date:'2026-09-02'}])assert.equal(retainedLibraryReview(doc,{...incoming,...change}),null);
assert.equal(retainedLibraryReview({...doc,content_hash:'b'.repeat(64)},incoming),null);
const plan={format:'road-ready-evidence-recovery',version:1,id:'partial-test',summary:[],coverageNote:'',transfer:{documents:[{record:{client_document_id:'packet'},original:{sha256:hash}}]},documentCorrections:[{clientId:'packet',sha256:hash,before:{kind:'supporting_packet'},after:{kind:'supporting_packet',fields,components:partial.extracted.evidenceFactsV1.components},proofs:[{sha256:hash,page:1,note:'Test source'}]}],loadCorrections:[],aliases:[]};
validateRecoveryPlan(plan);plan.documentCorrections[0].after.components[0].reviewed='yes';assert.throws(()=>validateRecoveryPlan(plan),/Invalid packet component/);
console.log('PASS — reviewed packet readiness, visible supporting checks, real missing/conflicting/unreviewed sources, source versus delivery dates, review retention and partial packet validation');
