'use client';
import React,{useState,useEffect} from 'react';
import {mirrorStatus,mirrorEvent,mirrorPaused,pauseMirror,runMirror,downloadMirror} from '../../../../lib/owner-op-cloud/cloudMirrorV110450.js';
export default function CloudBackupPanel(){
 const [status,setStatus]=useState(mirrorStatus),[paused,setPaused]=useState(false),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{setPaused(mirrorPaused());const update=e=>setStatus(e.detail);window.addEventListener(mirrorEvent,update);runMirror();return()=>window.removeEventListener(mirrorEvent,update);},[]);
 useEffect(()=>()=>{if(file)URL.revokeObjectURL(file.url);},[file]);
 async function download(){setBusy(true);setFile(null);setMessage('Checking the saved cloud copy…');try{const f=await downloadMirror(setMessage);setFile({url:URL.createObjectURL(f),name:f.name});setMessage('Cloud copy checked. Save this ZIP to Files.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const running=status.phase==='running';
 return <section className="rr-card" aria-label="Complete device backup"><span className="rr-eyebrow">TEMPORARY CLOUD BACKUP</span><h2>All records &amp; original files</h2><p>Each device keeps its own copy. Includes loads, both drivers’ saved logs, wallet, signatures, documents and settings.</p><p role="status" style={{overflowWrap:'anywhere'}}>{status.message}</p>{status.latest?<p>Last copy: {new Date(status.latest.created_at).toLocaleString()} · {status.latest.missing_originals?`${status.latest.missing_originals} originals unavailable`:'Files verified'}</p>:null}<div className="rr-actions"><button className="rr-primary" disabled={running||busy||paused} onClick={()=>runMirror({force:true})}>{running?'Backing up…':'Back up everything now'}</button><button disabled={running||busy||!status.latest} onClick={download}>Prepare cloud download</button></div><label className="rr-checkbox"><input type="checkbox" checked={!paused} onChange={e=>{const pause=!e.target.checked;pauseMirror(pause);setPaused(pause);if(!pause)runMirror({force:true});}}/>Keep this device backed up while open and online</label><p>Local files stay on this device. Pausing keeps previous cloud copies available. Before removing cloud storage, download the verified ZIP and check its restore on another device.</p>{message?<p role="status">{message}</p>:null}{file?<a className="rr-button" href={file.url} download={file.name}>Download verified backup</a>:null}</section>;
}
