import assert from 'node:assert/strict';
import fs from 'node:fs';
import {buildEvidence,validateFacts,makeBookEntry,day,clone,isReviewed,possibleFuelDuplicate,registerEvidenceTypes,CATALOG,assertSourceHash,evidenceLoadResolver,reconcileFuelSources} from './evidenceCore.js';
const recoverySource=fs.readFileSync(new URL('./recoveryCore.js',import.meta.url),'utf8').replace('./evidenceCoreV110413.js',new URL('./evidenceCore.js',import.meta.url).href);
const {validateRecoveryPlan,prepareRecoveryBusiness,checkDocumentCorrection}=await import('data:text/javascript;base64,'+Buffer.from(recoverySource).toString('base64'));
assert.equal(CATALOG.invoice.readerType,'load_invoice');assert.equal(CATALOG.maintenance.readerType,'repair_invoice');
const hash='a'.repeat(64),range={from:'2026-09-21',to:'2026-09-27'},load={id:'one',loadNo:'L100',pickupDate:'2026-09-25',deliveryDate:'2026-09-28',documentWorkflowStage:'booked'};
const source=(kind,fields={},reviewed=false,id=kind)=>({local_id:id,client_document_id:id+'-client',sha256:hash,load_no:fields.loadNo??'L100',document_date:fields.date??'2026-09-25',type:kind,extracted:{...fields,...(reviewed?{evidenceFactsV1:{version:1,reviewedAt:'2026-09-27T10:00:00Z',sourceSha256:hash,fields,components:[]}}:{})}});
const build=extra=>buildEvidence({range,loads:[load],today:'2026-09-27',...extra});
const baseline=build();assert.equal(baseline.checks.find(c=>c.kind==='pod').status,'not_due');assert.equal(baseline.checks.find(c=>c.kind==='bol').status,'missing');
const aliasSource=source('pod',{loadNo:'BOL-100',date:'2026-09-26',reference:'BOL-100',podSigned:true},true);
for(const area of ['load','ifta','tax','audit']){const scoped=build({area,documents:[aliasSource],businessStore:{evidenceAliases:[{from:'BOL-100',to:'L100'}]}});assert.equal(scoped.checks.find(c=>c.kind==='pod').status,'ready',area+' resolves saved aliases');}
assert.equal(evidenceLoadResolver({evidenceAliases:[{from:'A',to:'B'},{from:'B',to:'A'}]})('A'),'A');
const octoberFuel=source('fuel_receipt',{loadNo:'Q300',date:'2026-10-01',quantity:20},false);
for(const area of ['ifta','tax','audit']){const scoped=buildEvidence({area,documents:[octoberFuel],loads:[{loadNo:'Q300',pickupDate:'2026-09-30',deliveryDate:'2026-10-01'}],range:{from:'2026-07-01',to:'2026-09-30'}});assert.equal(scoped.docs.length,0,area+' excludes next-quarter transactions on this-quarter loads');assert.ok(scoped.issues.some(i=>i.id==='fuel-coverage'));}
const loadWide=buildEvidence({area:'load',loadNo:'Q300',documents:[octoberFuel],loads:[{loadNo:'Q300',pickupDate:'2026-09-30'}],range:{from:'2026-07-01',to:'2026-09-30'}});assert.equal(loadWide.docs.length,1,'load-wide view keeps its documents');
assert.doesNotThrow(()=>assertSourceHash({content_hash:hash},hash));assert.doesNotThrow(()=>assertSourceHash({contentHash:hash.toUpperCase()},hash));assert.throws(()=>assertSourceHash({content_hash:'b'.repeat(64)},hash),/checksum/);assert.throws(()=>assertSourceHash({sha256:hash,contentHash:'b'.repeat(64)},hash),/checksum/);
const completed=build({loads:[{...load,documentWorkflowStage:'delivered'}]});assert.equal(completed.checks.find(c=>c.kind==='pod').status,'missing');
assert.deepEqual(build({loads:[{...load,documentWorkflowStage:'tonu'}]}).checks.map(c=>c.kind),['rate_confirmation','invoice']);
assert.equal(build({loads:[{...load,pickupDate:'2026-09-14',deliveryDate:'2026-09-15'}]}).checks.length,0);
const rateFields={date:'2026-09-25',loadNo:'L100',merchant:'Test Broker',origin:'Alpha, NJ',destination:'Beta, IL',pickupDate:'2026-09-25',deliveryDate:'2026-09-28',total:500};
const rate=source('rate_confirmation',rateFields,true),pod=source('pod',{loadNo:'L100',date:'2026-09-26',reference:'BOL55',podSigned:true},true);
assert.equal(build({documents:[rate]}).checks.find(c=>c.kind==='rate_confirmation').status,'ready');
assert.equal(build({documents:[source('rate_confirmation',rateFields,false)]}).checks[0].status,'review');
assert.equal(build({documents:[{...rate,sha256:'b'.repeat(64)}]}).checks[0].status,'review','review cannot follow different original');
assert.equal(isReviewed({...rate,sha256:''}),false);
assert.equal(build({documents:[pod]}).checks.find(c=>c.kind==='pod').status,'ready');
assert.equal(build({documents:[source('bol',{loadNo:'L100',date:'2026-09-26',reference:'BOL55',origin:'Alpha',destination:'Beta'},true)]}).checks.find(c=>c.kind==='pod').status,'not_due','BOL is not proof of delivery');
const packet=source('supporting_packet',{date:'2026-09-25',loadNo:'L100'},true);
packet.extracted.evidenceFactsV1.components=[{kind:'rate_confirmation',reviewed:true,pages:[1],fields:rateFields},{kind:'pod',reviewed:false,pages:[2],fields:pod.extracted.evidenceFactsV1.fields}];
let model=build({documents:[packet]});assert.equal(model.checks[0].status,'ready');assert.equal(model.checks.find(c=>c.kind==='pod').status,'review','parent review cannot confirm a component');
const conflict=source('bol',{canonicalLoadNo:'OTHER',date:'',loadNo:'L100'});model=build({documents:[conflict]});assert.ok(model.issues.some(x=>x.id.endsWith(':identity')));assert.ok(model.issues.some(x=>x.id.endsWith(':date')));
const customs={evidenceExpectations:[{id:'receipt2',kind:'expense_receipt',label:'Second day receipt',date:'2026-09-26',area:'tax'}]};
const expenseFields={date:'2026-09-25',merchant:'Test Store',total:20,currency:'USD',purpose:'Supplies',payment:'paid',reference:'R22',loadNo:''};
model=build({documents:[source('expense_receipt',expenseFields,true)],businessStore:customs});assert.equal(model.checks.find(c=>c.id==='receipt2').status,'missing','one receipt cannot satisfy a different transaction day');
const fuelFields={date:'2026-09-25',loadNo:'',merchant:'Test Stop',sellerAddress:'1 Test Road',total:100,currency:'USD',quantity:37.85411784,volumeUnit:'L',fuelType:'diesel',state:'NJ',vehicle:'22',purchaser:'Test Carrier',taxPaid:true,qualifiedVehicle:true};
const twin={transactionId:'fuel-tx',date:'2026-09-25',state:'NJ',total:100,gallons:10,merchant:'Test Stop'};assert.equal(reconcileFuelSources([twin,{...twin,source:'fuel_csv_v102'}]).length,1);assert.equal(reconcileFuelSources([{date:twin.date,total:100},{date:twin.date,total:100}]).length,2);assert.equal(reconcileFuelSources([{...twin,externalId:'csv-1',transactionId:''},{...twin,sourceFuelImportId:'csv-1',transactionId:''}]).length,1);
const fuel=source('fuel_receipt',fuelFields,true);let entry=makeBookEntry(fuel,fuelFields);assert.equal(entry.bucket,'fuel');assert.ok(Math.abs(entry.row.gallons-10)<1e-8);assert.equal(entry.row.iftaEligible,true);
assert.equal(possibleFuelDuplicate(entry.row,{date:fuelFields.date,state:'NJ',total:100,gallons:10}),true);
assert.equal(possibleFuelDuplicate({...entry.row,transactionId:'TX55'},{date:fuelFields.date,transactionId:'TX55'}),true);
assert.equal(possibleFuelDuplicate(entry.row,{date:'2026-09-26',state:'NJ',total:100,gallons:10}),false);
registerEvidenceTypes([{id:'future_tax_document',label:'New tax source',stacks:['tax'],required:['date','invoiceNo']}]);assert.ok(CATALOG.future_tax_document.uses.includes('tax'));assert.ok(CATALOG.future_tax_document.fields.includes('reference'));
assert.equal(makeBookEntry(fuel,{...fuelFields,fuelType:'def'}).row.iftaEligible,false);
assert.equal(makeBookEntry(fuel,{...fuelFields,qualifiedVehicle:false}).row.iftaEligible,false);
assert.throws(()=>makeBookEntry(fuel,{...fuelFields,currency:'CAD'}),/conversion/);
assert.throws(()=>makeBookEntry(fuel,{...fuelFields,quantity:0}),/volume/);
assert.equal(day('2026-02-30'),'');assert.throws(()=>validateFacts('fuel_receipt',{state:'XX'}),/abbreviation/);assert.throws(()=>validateFacts('pod',{loadNo:'not a reference'}),/load number/);
assert.ok(build({ownerStore:{mileageImports:[{date:'2026-09-25',state:'NJ',miles:50}]}}).issues.every(i=>i.id!=='jurisdiction-mileage'));
assert.ok(build({businessStore:{fuel:[{id:'f',date:'2026-09-25',total:20}]}}).issues.some(i=>i.label==='Book entry needs its source'));
const plan={format:'road-ready-evidence-recovery',version:1,id:'test-recovery',summary:['Synthetic correction'],coverageNote:'Synthetic sources only.',transfer:{documents:[{record:{client_document_id:'doc-client'},original:{sha256:hash}}]},documentCorrections:[{clientId:'doc-client',sha256:hash,before:{kind:'bol',loadNo:'BOL55',date:'2026-09-24'},after:{kind:'pod',fields:{loadNo:'L100',date:'2026-09-25',reference:'BOL55',podSigned:true}},proofs:[{sha256:hash,page:1,note:'Synthetic stamp'}]}],loadCorrections:[{id:'one',loadNo:'BOL55',before:{loadNo:'BOL55',gross:0},after:{loadNo:'L100',gross:500},proofs:[{sha256:hash,page:1,note:'Synthetic agreement'}]}],aliases:[{from:'BOL55',to:'L100'}]};
validateRecoveryPlan(plan);const old={loads:[{id:'one',loadNo:'BOL55',gross:0,privateNote:'keep'}]};const next=prepareRecoveryBusiness(old,plan);assert.equal(next.loads.length,1);assert.equal(next.loads[0].loadNo,'L100');assert.equal(next.loads[0].privateNote,'keep');assert.equal(old.loads[0].loadNo,'BOL55');
assert.throws(()=>prepareRecoveryBusiness({loads:[{...old.loads[0],gross:700}]},plan),/changed/);
const again=prepareRecoveryBusiness({...next,loads:[{...next.loads[0],gross:800}],evidenceRecoveryHistory:[{id:plan.id}]},plan);assert.equal(again.loads[0].gross,800);
assert.throws(()=>prepareRecoveryBusiness({loads:[],evidenceAliases:[{from:'L100',to:'BOL55'}]},plan),/cycle/);
const correction=plan.documentCorrections[0];checkDocumentCorrection(source('bol',{loadNo:'BOL55',date:'2026-09-24'}),correction);
assert.throws(()=>checkDocumentCorrection(source('bol',{loadNo:'NEW999',date:'2026-09-24'}),correction),/changed/);
assert.throws(()=>checkDocumentCorrection({...pod,sha256:'c'.repeat(64)},correction),/differs/);
const malformed=clone(plan);malformed.loadCorrections[0].after.deliveryDate='2026-09-28';assert.throws(()=>validateRecoveryPlan(malformed),/expected value/);
const unsafe=clone(plan);unsafe.documentCorrections[0].after.fields['unexpected']='wrong';assert.throws(()=>validateRecoveryPlan(unsafe),/Unsupported/);
const cycle=clone(plan);cycle.aliases.push({from:'L100',to:'BOL55'});assert.throws(()=>validateRecoveryPlan(cycle),/cycle/);
console.log('PASS — stage-aware requirements, TONU, source-bound review, multi-part packets, transaction dates, actual mileage, fuel eligibility, immutable recovery, conflict protection and repeat imports');
