import assert from 'node:assert/strict';
import fs from 'node:fs';
const url=new URL('../v110413/evidenceCore.js',import.meta.url).href;
const source=fs.readFileSync(new URL('../v110413/recoveryCore.js',import.meta.url),'utf8').replace('./evidenceCoreV110413.js',url);
const {reviewRecoveryRecords,confirmRecoveryReview,prepareRecoveryBusiness,checkDocumentCorrection}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const hash='a'.repeat(64),doc={local_id:'one',client_document_id:'doc',type:'other',load_no:'OLD-BOL',date:'2026-09-23',sha256:hash,original_file_name:'source.pdf'};
const proof=[{sha256:hash,page:1,note:'Synthetic reviewed source'}];
const p={format:'road-ready-evidence-recovery',version:1,id:'test-review',summary:['Synthetic only'],coverageNote:'Originals preserved',transfer:{documents:[{record:doc,original:{sha256:hash,base64:'AA=='}}]},documentCorrections:[{clientId:'doc',sha256:hash,before:{kind:'bol',loadNo:'DISPLAY',date:''},after:{kind:'pod',fields:{loadNo:'NEW',date:'2026-09-24',reference:'OLD-BOL',podSigned:true}},proofs:proof}],loadCorrections:[{id:'load',loadNo:'DISPLAY',before:{revenue:0,documentTransferDays:['2026-09-23']},after:{revenue:500,documentTransferDays:['2026-09-24']},proofs:proof}],aliases:[]};
const current={loads:[{id:'load',loadNo:'DISPLAY',keep:'private'}]};
const review=reviewRecoveryRecords(current,[doc],p);
assert.equal(review.conflicts.length,5,'all hidden raw/export differences are shown together');
assert.throws(()=>confirmRecoveryReview(current,[doc],p,review),/Use recovered details/);
assert.throws(()=>checkDocumentCorrection(doc,p.documentCorrections[0]),/changed/);
const approved=confirmRecoveryReview(current,[doc],p,review,true);
assert.doesNotThrow(()=>checkDocumentCorrection(doc,p.documentCorrections[0],approved));
assert.equal(prepareRecoveryBusiness(current,p,approved).loads[0].revenue,500);
assert.equal(current.loads[0].revenue,undefined,'preview and confirmation never mutate saved state');
assert.throws(()=>confirmRecoveryReview(current,[{...doc,title:'New local edit'}],p,review,true),/after this preview/);
assert.throws(()=>confirmRecoveryReview({loads:[{...current.loads[0],revenue:600}]},[doc],p,review,true),/after this preview/);
const changed=structuredClone(p);changed.documentCorrections[0].after.fields.reference='OTHER';assert.throws(()=>confirmRecoveryReview(current,[doc],changed,review,true),/after this preview/);
assert.throws(()=>reviewRecoveryRecords(current,[{...doc,sha256:'b'.repeat(64)}],p),/original differs/);
assert.throws(()=>checkDocumentCorrection({...doc,content_hash:'b'.repeat(64)},p.documentCorrections[0],approved),/original differs/);
assert.throws(()=>reviewRecoveryRecords(current,[doc,{...doc,local_id:'duplicate'}],p),/identities/);
const reviewed={...doc,extracted:{evidenceFactsV1:{source:'driver_review',fields:{reference:'LATER',notes:'Driver edit'}}}};
const later=reviewRecoveryRecords(current,[reviewed],p);assert.equal(later.conflicts.length,6);assert.ok(later.conflicts.some(c=>c.field==='review'&&c.saved.fields.notes==='Driver edit'));
assert.throws(()=>checkDocumentCorrection(reviewed,p.documentCorrections[0],approved),/newer reviewed/);
assert.doesNotThrow(()=>checkDocumentCorrection(reviewed,p.documentCorrections[0],confirmRecoveryReview(current,[reviewed],p,later,true)));
const componentEdit={...doc,extracted:{evidenceFactsV1:{source:'driver_review',fields:p.documentCorrections[0].after.fields,components:[{kind:'bol',pages:[2],reviewed:true,fields:{reference:'DRIVER'}}]}}};
assert.ok(reviewRecoveryRecords(current,[componentEdit],p).conflicts.some(c=>c.field==='review'),'reviewed packet components also require confirmation');
assert.throws(()=>checkDocumentCorrection(componentEdit,p.documentCorrections[0],approved),/newer reviewed/);
const already=reviewRecoveryRecords({...current,evidenceRecoveryHistory:[{id:p.id}]},[reviewed],p);assert.equal(already.conflicts.length,0);assert.equal(already.already,true);
assert.equal(reviewRecoveryRecords({loads:[]},[],p).conflicts.length,3,'new sources are also previewed if package expectations differ');
console.log('PASS — all recovery conflicts, explicit consent, immutable originals, changed preview rejection, newer source review and repeat recovery');
