export const RECORDS_VAULT_SCHEMA_VERSION = 1;

export const DOCUMENT_TYPES = Object.freeze({
  LOG: 'LOG',
  BOL: 'BOL',
  POD: 'POD',
  RATE_CONFIRMATION: 'RATE_CONFIRMATION',
  FUEL_RECEIPT: 'FUEL_RECEIPT',
  TOLL_RECEIPT: 'TOLL_RECEIPT',
  SCALE_TICKET: 'SCALE_TICKET',
  LUMPER_RECEIPT: 'LUMPER_RECEIPT',
  PARKING_RECEIPT: 'PARKING_RECEIPT',
  REPAIR_RECEIPT: 'REPAIR_RECEIPT',
  INSPECTION: 'INSPECTION',
  SETTLEMENT: 'SETTLEMENT',
  OTHER: 'OTHER',
});

export const WEEK_STATUS = Object.freeze({
  OPEN: 'OPEN',
  SEALED: 'SEALED',
});

export const DOCUMENT_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  DELETED: 'DELETED',
});

export const REQUIRED_OWNER_OPERATOR_TYPES = Object.freeze([
  DOCUMENT_TYPES.LOG,
  DOCUMENT_TYPES.BOL,
  DOCUMENT_TYPES.POD,
  DOCUMENT_TYPES.FUEL_RECEIPT,
]);
