import { mileageEvidenceForLoadV10976, trailerReturnEvidenceV10976 } from './loadEvidenceV10976.js';
import { supportingDocumentCountsV10977 } from './supportingDocumentsV10977.js';

export const LOAD_FOLDER_ENGINE_VERSION_V10969 = '109.7.7';
function text(v=''){return String(v??'').replace(/\s+/g,' ').trim();}
function upper(v=''){return text(v).toUpperCase();}
function num(v=0){const n=Number(v);return Number.isFinite(n)?n:0;}
function date(v=''){const s=text(v);const raw=s.slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(raw)?raw:'';}
function unique(v=[]){return [...new Set(v.filter(Boolean))];}
function docType(d={}){return text(d.document_type||d.type||d.classification?.selectedType||d.extracted?.type||d.metadata?.relationType).toLowerCase();}
function docLoad(d={}){return upper(d.load_no||d.loadNo||d.canonicalLoadNo||d.extracted?.canonicalLoadNo||d.extracted?.loadNo||d.metadata?.loadNo);}
function docDay(d={}){return date(d.vaultDate||d.document_date||d.documentDate||d.extracted?.documentDate||d.extracted?.date||d.created_at);}
function docStop(d={}){return num(d.stopSequence||d.stop_sequence||d.extracted?.stopSequence||d.metadata?.stopSequence);}
function place(c='',s=''){return [text(c),upper(s).slice(0,2)].filter(Boolean).join(', ');}
function refs(x={}){return [x.loadNo,x.shippingDocs,x.orderNo,x.pickedUpLoadNo,x.deliveredLoadNo].map(upper);}
function loadEvents(state={},loadNo=''){const t=upper(loadNo);return Object.entries(state.eventsByDay||{}).flatMap(([day,events])=>(events||[]).filter(e=>refs(e).includes(t)).map(e=>({...e,day})));}
function loadRouteLegs(state={},loadNo=''){const t=upper(loadNo);return Object.entries(state.routeLegsByDay||{}).flatMap(([day,legs])=>(legs||[]).filter(l=>upper(l.loadNo||l.orderNo||l.shippingDocs)===t).map(l=>({...l,day})));}
function deliveryStops(load={},legs=[]){const source=(load.stops||[]).filter(s=>s.type==='delivery');if(source.length)return source.map((s,i)=>({sequence:num(s.deliverySequence||s.stopSequence||s.sequence||i+1),company:text(s.company||s.facility||s.name),city:text(s.city||s.deliveryCity),state:upper(s.state||s.deliveryState).slice(0,2),address:text(s.address),appointment:text(s.appointment||s.time)})).sort((a,b)=>a.sequence-b.sequence);return legs.filter(l=>num(l.stopSequence)>1&&!/empty return/i.test(text(l.stopCompany))).map((l,i)=>({sequence:num(l.stopSequence||i+1),company:text(l.stopCompany),city:text(l.toCity),state:upper(l.toState).slice(0,2),address:text(l.stopAddress),appointment:text(l.appointment)})).sort((a,b)=>a.sequence-b.sequence);}
function fuelRowsForLoad(store={},loadNo='',days=[]){const t=upper(loadNo);return (store.fuel||[]).filter(r=>upper(r.loadNo)===t||(!r.loadNo&&days.includes(date(r.date))));}
function expenseRowsForLoad(store={},loadNo='',days=[]){const t=upper(loadNo);return (store.expenses||[]).filter(r=>upper(r.loadNo)===t||(!r.loadNo&&days.includes(date(r.date))));}
function trailerIdOf(load={},events=[]){return text(load.trailerId||load.trailer||load.trailerNo||load.equipment?.trailerId||events.find(e=>e.hookedTrailer||e.droppedTrailer)?.hookedTrailer||events.find(e=>e.hookedTrailer||e.droppedTrailer)?.droppedTrailer);}

export function buildLoadFoldersV10969({loads=[],documents=[],state={},businessStore={}}={}){
 const map=new Map();for(const l of loads||[]){const n=upper(l.loadNo||l.canonicalLoadNo);if(n)map.set(n,{...l,loadNo:n});}for(const d of documents||[]){const n=docLoad(d);if(n&&!map.has(n))map.set(n,{id:`load_${n}`,loadNo:n,status:'needs_review'});}for(const legs of Object.values(state.routeLegsByDay||{}))for(const l of legs||[]){const n=upper(l.loadNo||l.orderNo||l.shippingDocs);if(n&&!map.has(n))map.set(n,{id:`load_${n}`,loadNo:n,status:'tracked'});}
 return [...map.values()].map(load=>{const loadNo=upper(load.loadNo),docs=(documents||[]).filter(d=>docLoad(d)===loadNo),events=loadEvents(state,loadNo),legs=loadRouteLegs(state,loadNo),stops=deliveryStops(load,legs);const operationalDays=unique([...events.map(e=>e.day),...legs.map(l=>l.day)]).sort(),days=unique([...operationalDays,...docs.map(docDay)]).sort();const rateCons=docs.filter(d=>['rate_confirmation','load_tender'].includes(docType(d))),bols=docs.filter(d=>docType(d)==='bol'),pods=docs.filter(d=>['pod','delivery_receipt'].includes(docType(d))),fuelDocs=docs.filter(d=>docType(d)==='fuel_receipt');
  const supporting=supportingDocumentCountsV10977(docs);
  const assigned=new Map(),unassigned=[];for(const d of pods){const s=docStop(d);if(s&&!assigned.has(s))assigned.set(s,d);else unassigned.push(d);}for(const stop of stops){if(!assigned.has(stop.sequence)&&unassigned.length)assigned.set(stop.sequence,unassigned.shift());}const missingStops=stops.filter(s=>!assigned.has(s.sequence)),podComplete=stops.length?missingStops.length===0:pods.length>0;
  const mileage=mileageEvidenceForLoadV10976(state,loadNo),logbookComplete=events.length>0;const fuelRows=fuelRowsForLoad(businessStore,loadNo,days),expenses=expenseRowsForLoad(businessStore,loadNo,days),fuelActivity=fuelRows.length>0,fuelComplete=!fuelActivity||fuelDocs.length>0||fuelRows.every(r=>r.receiptAttached===true);
  const trailerId=trailerIdOf(load,events),trailerReturn=trailerReturnEvidenceV10976({state,loadNo,trailerId,events});
  const checklist=[{id:'rate',label:'Rate Confirmation',complete:rateCons.length>0,required:true,detail:rateCons.length?`${rateCons.length} saved`:'Required to define the load'},{id:'bol',label:'Bill of Lading',complete:bols.length>0,required:true,detail:bols.length?`${bols.length} saved`:'Pickup paperwork missing'},{id:'pod',label:'Proof of Delivery',complete:podComplete,required:true,detail:stops.length?`${assigned.size} of ${stops.length} stops`:`${pods.length} saved`},{id:'logbook',label:'Supporting Logbook',complete:logbookComplete,required:true,detail:logbookComplete?`${operationalDays.length||days.length} linked day${(operationalDays.length||days.length)===1?'':'s'}`:'No exact load events linked'},{id:'miles',label:'Daily Driving Miles',complete:mileage.complete,required:true,detail:mileage.complete?`${mileage.total.toFixed(2)} mi from Logbook (${mileage.rows.map(r=>r.day).join(', ')})`:'No mileage found on linked Logbook days'},{id:'fuel',label:'Fuel Receipt',complete:fuelComplete,required:fuelActivity,optional:!fuelActivity,detail:fuelActivity?(fuelComplete?'Fuel evidence attached':'Fuel transaction found — receipt missing'):'No fuel activity detected'},{id:'trailer_return',label:'Trailer Return',complete:!trailerReturn.required||trailerReturn.returned,required:trailerReturn.required,detail:!trailerReturn.required?'No trailer return required':trailerReturn.returned?`Trailer ${trailerId} returned`:`Trailer ${trailerId} return pending — trailer remains available for load-out and other loads`}];
  const completeCount=checklist.filter(i=>i.complete).length,percent=Math.round(completeCount/checklist.length*100),missing=checklist.filter(i=>i.required&&!i.complete),onlyTrailer=missing.length===1&&missing[0].id==='trailer_return';const origin=text(load.origin)||place(legs[0]?.fromCity,legs[0]?.fromState),destination=text(load.destination)||place(legs.at(-1)?.toCity,legs.at(-1)?.toState),title=[origin,destination].filter(Boolean).join(' → ')||`Load ${loadNo}`;
  return {id:load.id||`load_${loadNo}`,loadNo,title,origin,destination,broker:text(load.broker),status:missing.length?(onlyTrailer?'in_progress':'needs_attention'):'complete',percent,missing,checklist,documents:docs,events,legs,stops,pods,podAssignments:assigned,bols,rateCons,fuelDocs,fuelRows,expenses,supportingDocuments:supporting.organized,days:operationalDays.length?operationalDays:days,missingStops,unassignedPods:unassigned,mileage,trailerId,trailerReturn,counts:{documents:docs.length,stops:stops.length,pods:pods.length,bols:bols.length,rateCons:rateCons.length,fuel:fuelDocs.length,supporting:supporting.total}};
 }).sort((a,b)=>{const rank={needs_attention:0,in_progress:1,legacy_review:2,complete:3};return (rank[a.status]??1)-(rank[b.status]??1)||(b.days.at(-1)||'').localeCompare(a.days.at(-1)||'')||b.loadNo.localeCompare(a.loadNo);});
}
