'use client';

import React, { useEffect, useMemo, useState } from 'react';
import { reconcileLoadFoldersV10974 } from './loadFolderReconciliationV10974.js';
import { openVaultDocumentV102, vaultDocumentLabelV102, vaultDocumentTypeV102 } from './documentVaultV102.js';
import { exportRoadReadyAuditPackageV10973 } from './auditExportV10973.js';
import RepairImportPanelV10975 from './RepairImportPanelV10975.jsx';
import { markTrailerReturnedV10976, undoTrailerReturnedV10976 } from './loadEvidenceV10976.js';
import { normalizedDocumentTypeV10977, logicalDeduplicateDocumentsV10977 } from './supportingDocumentsV10977.js';
import './loadFoldersV10969.css';
import './loadFolderReviewV10974.css';

const VERSION='109.8.0';
function text(value=''){return String(value??'').replace(/\s+/g,' ').trim();}
function dateLabel(value=''){const raw=text(value);if(!/^\d{4}-\d{2}-\d{2}/.test(raw))return 'Date not confirmed';const iso=raw.slice(0,10),d=new Date(`${iso}T12:00:00`);return Number.isNaN(d.getTime())?'Date not confirmed':d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});}
function isCoreDocument(document={}){return ['rate_confirmation','bol','pod'].includes(normalizedDocumentTypeV10977(document));}
function mondayOf(iso=''){const d=/^\d{4}-\d{2}-\d{2}$/.test(iso)?new Date(`${iso}T12:00:00`):new Date();const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d.toISOString().slice(0,10);}
function weekLabel(start=''){const a=new Date(`${start}T12:00:00`),b=new Date(a);b.setDate(a.getDate()+6);const sameMonth=a.getMonth()===b.getMonth();return `Week of ${a.toLocaleDateString(undefined,{month:'long',day:'numeric'})}${sameMonth?'–'+b.getDate():'–'+b.toLocaleDateString(undefined,{month:'long',day:'numeric'})}, ${b.getFullYear()}`;}
function docType(document={}){return text(document.type||document.document_type||document.extracted?.type||document.classification?.selectedType).toLowerCase();}
function docDate(document={}){return text(document.vaultDate||document.documentDate||document.document_date||document.extracted?.documentDate||document.extracted?.date||document.metadata?.logDate).slice(0,10);}
function exactLoadDays(folder={}){return [...new Set([...(folder.days||[]),...(folder.events||[]).map(x=>String(x.day||'').slice(0,10)),...(folder.legs||[]).flatMap(x=>[x.pickupDay,x.deliveryDay,x.day]),...(folder.mileage?.linkedDays||[]),...(folder.mileage?.rows||[]).map(x=>String(x.day||'').slice(0,10))].filter(d=>/^\d{4}-\d{2}-\d{2}$/.test(d)))].sort();}
function snapshotDocuments(folder={},kind='logbook_snapshot'){const all=[...(folder.documents||[]),...((folder.supportingDocuments||[]).flatMap(g=>g.documents||[]))];return logicalDeduplicateDocumentsV10977(all.filter(d=>docType(d)===kind)).sort((a,b)=>docDate(a).localeCompare(docDate(b)));}
function preferredSnapshot(folder={},kind='logbook_snapshot'){const docs=snapshotDocuments(folder,kind);if(!docs.length)return null;const days=exactLoadDays(folder),wanted=kind==='miles_snapshot'?(folder.mileage?.rows||[]).map(x=>String(x.day||'').slice(0,10)).filter(Boolean).at(-1):days.at(-1);return docs.find(d=>docDate(d)===wanted)||docs.at(-1);}
function DocumentRow({document,icon}){return <article><div className="owner-os-doc-icon-v102">{icon||vaultDocumentTypeV102(document).slice(0,3).toUpperCase()}</div><div><span>{vaultDocumentLabelV102(document)}</span><b>{document.title||document.original_file_name||document.fileName||'Supporting document'}</b><em>{dateLabel(document.vaultDate||document.documentDate||document.document_date||document.created_at)}</em></div><button type="button" onClick={()=>openVaultDocumentV102(document)}>Open</button></article>;}

export default function LoadFoldersV10969({loads=[],documents=[],state={},businessStore={},loading=false,onScan,onOpenLog,onContinueBilling}){
 const [query,setQuery]=useState(''),[openWeek,setOpenWeek]=useState(''),[openLoadNo,setOpenLoadNo]=useState(''),[showReview,setShowReview]=useState(false),[reviewIndex,setReviewIndex]=useState(0),[auditBusy,setAuditBusy]=useState(false),[auditMessage,setAuditMessage]=useState(''),[revision,setRevision]=useState(0),[openSupport,setOpenSupport]=useState({});
 useEffect(()=>{const refresh=()=>setRevision(v=>v+1);window.addEventListener('road-ready-trailer-return-changed',refresh);window.addEventListener('road-ready-repair-applied',refresh);return()=>{window.removeEventListener('road-ready-trailer-return-changed',refresh);window.removeEventListener('road-ready-repair-applied',refresh);};},[]);
 const model=useMemo(()=>reconcileLoadFoldersV10974({loads,documents,state,businessStore}),[loads,documents,state,businessStore,revision]);
 const {folders,reviewItems,allDocuments}=model;
 const weeks=useMemo(()=>{const map=new Map();for(const folder of folders){const start=mondayOf(folder.days.at(-1)||folder.days[0]||'');if(!map.has(start))map.set(start,[]);map.get(start).push(folder);}return [...map.entries()].sort((a,b)=>b[0].localeCompare(a[0])).map(([start,items])=>({start,label:weekLabel(start),items,complete:items.filter(x=>x.status==='complete').length,attention:items.filter(x=>['needs_attention','in_progress','legacy_review'].includes(x.status)).length,amazon:items.filter(x=>x.isAmazon).length,miles:items.reduce((s,x)=>s+Number(x.mileage?.total||0),0),revenue:items.reduce((s,x)=>s+Number(x.revenue||0),0)}));},[folders]);
 const selectedWeek=weeks.find(w=>w.start===openWeek)||null;
 const filtered=useMemo(()=>{const list=selectedWeek?.items||[];const q=text(query).toLowerCase();return q?list.filter(f=>[f.loadNo,f.title,f.broker,...f.days].join(' ').toLowerCase().includes(q)):list;},[selectedWeek,query]);
 const open=folders.find(f=>f.loadNo===openLoadNo)||null;
 const currentReview=reviewItems[Math.min(reviewIndex,Math.max(0,reviewItems.length-1))]||null;
 async function exportAudit(){if(auditBusy)return;setAuditBusy(true);setAuditMessage('Building complete audit package…');try{const result=await exportRoadReadyAuditPackageV10973({folders,documents:allDocuments,state,businessStore});setAuditMessage(`Exported ${result.originals} originals. ${result.report.summary.errors} errors and ${result.report.summary.warnings} warnings included.`);}catch(error){setAuditMessage(`Audit export failed: ${String(error?.message||error)}`);}finally{setAuditBusy(false);}}
 function openHistorical(folder,kind){return()=>{const snapshot=preferredSnapshot(folder,kind);if(snapshot)return openVaultDocumentV102(snapshot);const day=kind==='miles_snapshot'?((folder.mileage?.rows||[]).map(x=>x.day).filter(Boolean).at(-1)||exactLoadDays(folder).at(-1)):exactLoadDays(folder).at(-1);onOpenLog?.(day||'');};}
 function completedItemAction(item,folder){if(item.id==='rate'&&folder.rateCons?.[0])return()=>openVaultDocumentV102(folder.rateCons[0]);if(item.id==='bol'&&folder.bols?.[0])return()=>openVaultDocumentV102(folder.bols[0]);if(item.id==='pod'&&folder.pods?.[0])return()=>openVaultDocumentV102(folder.pods[0]);if(item.id==='logbook')return openHistorical(folder,'logbook_snapshot');if(item.id==='miles')return openHistorical(folder,'miles_snapshot');if(item.id==='fuel'&&folder.fuelDocs?.[0])return()=>openVaultDocumentV102(folder.fuelDocs[0]);return null;}
 function itemAction(item){if(item.id==='logbook')return openHistorical(open,'logbook_snapshot');if(item.id==='miles')return openHistorical(open,'miles_snapshot');if(item.id==='trailer_return')return()=>markTrailerReturnedV10976(open.loadNo,open.trailerId);return onScan;}
 function actionLabel(item){if(item.id==='logbook')return'Open Logbook';if(item.id==='miles')return'Open Miles';if(item.id==='trailer_return')return'Mark returned';return'Add';}
 function completedActionLabel(item){if(item.id==='rate')return'Open Rate Con';if(item.id==='bol')return'Open BOL';if(item.id==='pod')return'Open POD';if(item.id==='logbook')return'Open Logbook PDF';if(item.id==='miles')return'Open Miles PDF';if(item.id==='fuel')return'Open Fuel';return'Open';}
 function resolveReview(action){if(!currentReview)return;window.dispatchEvent(new CustomEvent('road-ready-document-review-action',{detail:{action,documentId:currentReview.local_id||currentReview.id,detectedLoad:currentReview.load_no||currentReview.loadNo,detectedType:normalizedDocumentTypeV10977(currentReview)}}));setReviewIndex(i=>Math.min(i+1,Math.max(0,reviewItems.length-1)));setRevision(v=>v+1);}

 if(open){const coreDocuments=logicalDeduplicateDocumentsV10977(open.documents.filter(isCoreDocument));return <section className="load-folder-detail-v10969">
  <button type="button" className="load-folder-back-v10969" onClick={()=>setOpenLoadNo('')}>‹ Loads in week</button>
  <header className={`load-folder-detail-head-v10969 ${open.status}`}><div><span>{open.isAmazon?'AMAZON RELAY LOAD':open.legacy?'LEGACY LOAD':`LOAD ${open.loadNo}`}</span><h2>{open.title}</h2><p>{open.isAmazon?'Amazon Relay load':open.broker||'Broker load'}</p></div><strong>{open.percent}%<small>{open.status==='complete'?'COMPLETE':open.status==='in_progress'?'IN PROGRESS':open.status==='legacy_review'?'LEGACY REVIEW':'READY SCORE'}</small></strong></header>
  <div className="load-folder-checklist-v10969">{open.checklist.map(item=>{const completeAction=completedItemAction(item,open);return <article key={item.id} className={item.complete?'done':item.required?'missing':'optional'}><i>{item.complete?'✓':item.required?'!':'○'}</i><div><b>{item.label}</b><span>{item.detail}</span></div>{!item.complete&&item.required?<button type="button" onClick={itemAction(item)}>{actionLabel(item)}</button>:item.id==='trailer_return'&&item.complete&&open.trailerReturn?.required?<button type="button" onClick={()=>undoTrailerReturnedV10976(open.loadNo)}>Undo</button>:completeAction?<button type="button" onClick={completeAction}>{completedActionLabel(item)}</button>:null}</article>;})}</div>
  <details open><summary>Load Overview</summary><div className="load-folder-summary-v10969"><div><b>{open.loadNo}</b><span>Load number</span></div><div><b>{open.isAmazon?'Amazon Relay':open.legacy?'Legacy':open.broker||'Broker'}</b><span>Type</span></div><div><b>{open.trailerId||'—'}</b><span>Trailer</span></div></div></details>
  <details open><summary>Core Load Documents</summary>{open.stops.length?<div className="load-folder-stops-v10969">{open.stops.map(stop=>{const matched=open.podAssignments?.get?.(Number(stop.sequence))||null;return <article key={stop.sequence} className={matched?'done':'missing'}><i>{matched?'✓':'!'}</i><div><span>STOP {stop.sequence}</span><b>{stop.company||`Delivery stop ${stop.sequence}`}</b></div>{matched?<button type="button" onClick={()=>openVaultDocumentV102(matched)}>Open POD</button>:!open.isAmazon?<button type="button" onClick={onScan}>Add POD</button>:null}</article>;})}</div>:null}<div className="load-folder-docs-v10969">{coreDocuments.map((document,index)=><DocumentRow key={document.local_id||document.id||`${normalizedDocumentTypeV10977(document)}-${index}`} document={document}/>)}</div></details>
  <details open><summary>Historical Audit Evidence</summary><div className="load-folder-actions-v10969"><button type="button" onClick={openHistorical(open,'logbook_snapshot')}>Open Logbook PDF</button><button type="button" onClick={openHistorical(open,'miles_snapshot')}>Open Miles PDF</button><button type="button" onClick={onScan}>Add Support</button></div></details>
  <details><summary>Supporting Documents ({open.counts.supporting||0})</summary>{open.supportingDocuments?.length?<div className="load-folder-support-groups-v10977">{open.supportingDocuments.map(group=>{const expanded=openSupport[group.id]!==false;return <section key={group.id}><button type="button" className="load-folder-support-head-v10977" onClick={()=>setOpenSupport(current=>({...current,[group.id]:!expanded}))}><span><i>{group.icon}</i><b>{group.label}</b></span><em>{group.documents.length} {expanded?'▴':'▾'}</em></button>{expanded?<div className="load-folder-docs-v10969">{group.documents.map((document,index)=><DocumentRow key={document.local_id||document.id||`${group.id}-${index}`} document={document} icon={group.icon}/>)}</div>:null}</section>;})}</div>:<div className="load-folder-support-empty-v10977">No supporting documents saved for this load.</div>}</details>
  <details><summary>Billing</summary><div className="load-folder-actions-v10969"><button type="button" onClick={()=>onContinueBilling?.(open.loadNo)}>Open Billing</button></div></details>
 </section>;}

 return <><div className="owner-os-section-head-v102"><div><span>DOCUMENTS · v{VERSION}</span><b>{openWeek?'LOADS OF SELECTED WEEK':'WEEKLY LOAD FOLDERS'}</b></div><div className="load-folder-head-actions-v10973"><RepairImportPanelV10975 onApplied={()=>setRevision(v=>v+1)}/><button type="button" disabled={auditBusy} onClick={exportAudit}>{auditBusy?'Exporting…':'Audit Export'}</button><button type="button" onClick={onScan}>+ Add</button></div></div>
 <div className="load-folder-audit-message-v10973">Historical evidence v109.8.0 · Load-day PDF snapshots open from the load folder · Current day is never used as a fallback when a load date exists.</div>
 {auditMessage?<div className="load-folder-audit-message-v10973">{auditMessage}</div>:null}
 {reviewItems.length?<div className="load-folder-review-v10974"><button type="button" onClick={()=>setShowReview(v=>!v)}><b>{reviewItems.length} documents need identity review</b><span>{showReview?'Close wizard':'Open wizard'}</span></button>{showReview&&currentReview?<div><article><div><b>Detected load: {currentReview.load_no||currentReview.loadNo||'Unknown'}</b><span>Confidence: {currentReview.classification?.confidence?Math.round(currentReview.classification.confidence*100):'—'}% · Type: {normalizedDocumentTypeV10977(currentReview)} · Stop: {currentReview.stopSequence||currentReview.stop_sequence||'—'}</span><em>{currentReview.original_file_name||currentReview.fileName||'Unnamed document'}</em></div><button type="button" onClick={()=>openVaultDocumentV102(currentReview)}>Open</button></article><div className="load-folder-actions-v10969"><button onClick={()=>resolveReview('accept')}>Accept</button><button onClick={()=>resolveReview('change_load')}>Change load</button><button onClick={()=>resolveReview('change_type')}>Change type</button><button onClick={()=>resolveReview('change_stop')}>Change stop</button><button onClick={()=>resolveReview('duplicate')}>Mark duplicate</button><button onClick={()=>resolveReview('supporting')}>Supporting only</button><button onClick={()=>resolveReview('ignore')}>Ignore</button></div></div>:null}</div>:null}
 {!openWeek?<>{loading?<div className="owner-os-loading-v102">Reconciling weekly folders…</div>:weeks.length?<div className="load-folder-grid-v10969">{weeks.map(week=><button type="button" className="load-folder-card-v10969 complete" key={week.start} onClick={()=>setOpenWeek(week.start)}><header><div><span>WEEK</span><b>{week.label}</b></div><i>›</i></header><div className="load-folder-counts-v10969"><span>{week.items.length} loads</span><span>{week.complete} complete</span><span className={week.attention?'missing':''}>{week.attention} attention</span><span>{week.amazon} Amazon</span><span>{reviewItems.length} review</span><span>{week.miles.toFixed(0)} mi</span>{week.revenue>0?<span>${week.revenue.toLocaleString('en-US')}</span>:null}</div></button>)}</div>:<div className="owner-os-empty-v102"><b>No weekly load folders yet</b></div>}</>:<><button type="button" className="load-folder-back-v10969" onClick={()=>{setOpenWeek('');setQuery('');}}>‹ All weeks</button><div className="load-folder-search-v10969"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this week…"/></div><div className="load-folder-grid-v10969">{filtered.map(folder=><button type="button" className={`load-folder-card-v10969 ${folder.status}`} key={folder.loadNo} onClick={()=>setOpenLoadNo(folder.loadNo)}><header><div><span>{folder.isAmazon?'AMAZON RELAY':folder.legacy?'LEGACY LOAD':'LOAD FOLDER'}</span><b>Load {folder.loadNo}</b></div><i>{folder.status==='complete'?'✓':folder.status==='legacy_review'?'R':folder.status==='in_progress'?'↻':'!'}</i></header><h3>{folder.title}</h3><p>{folder.isAmazon?'Amazon Relay load':folder.legacy?'Legacy load — review':folder.broker||'Broker load'}</p><div className="load-folder-counts-v10969"><span>{folder.counts.stops} stops</span><span>{folder.counts.bols} BOL</span><span className={folder.missingStops.length?'missing':''}>{folder.counts.stops-folder.missingStops.length}/{folder.counts.stops||0} POD</span><span>{folder.counts.supporting||0} support</span><span>{folder.mileage?.total?.toFixed?.(0)||0} mi</span></div></button>)}</div></>}
 </>;
}