'use client';

import {saveScannedDocument} from '../scan/scanStorage.js';
import {listVaultDocumentsV102} from './documentVaultV102.js';

const KEY='road_ready_repair_overlay_v1';
const HISTORY='road_ready_repair_history_v1';
function text(v=''){return String(v??'').replace(/\s+/g,' ').trim();}
function upper(v=''){return text(v).toUpperCase();}
function safeJson(raw){try{return JSON.parse(raw);}catch{return null;}}
function bytesToText(bytes){return new TextDecoder().decode(bytes);}
function normalizePlan(input={}){const plan=input.repairPlan||input.repair_plan||input;if(!plan||typeof plan!=='object')throw new Error('Repair plan is not valid JSON.');const version=text(plan.schema||plan.type||plan.format);if(version&&!/road[_-]?ready[_-]?repair/i.test(version))throw new Error('This file is not a Road Ready repair plan.');const documentAssignments=(plan.documentAssignments||plan.document_assignments||[]).map(x=>({documentId:text(x.documentId||x.document_id||x.id),loadNo:upper(x.loadNo||x.load_no),documentType:text(x.documentType||x.document_type).toLowerCase(),stopSequence:Number(x.stopSequence||x.stop_sequence||0)||0,documentDate:text(x.documentDate||x.document_date).slice(0,10),ignore:!!x.ignore})).filter(x=>x.documentId);const loadCorrections=(plan.loadCorrections||plan.load_corrections||[]).map(x=>({loadNo:upper(x.loadNo||x.load_no),origin:text(x.origin),destination:text(x.destination),broker:text(x.broker),deliveryStops:Number(x.deliveryStops||x.delivery_stops||0)||0,legacy:!!x.legacy,ignore:!!x.ignore,aliasFrom:upper(x.aliasFrom||x.alias_from)})).filter(x=>x.loadNo||x.aliasFrom);return{schema:'road_ready_repair_v1',createdAt:text(plan.createdAt||plan.created_at)||new Date().toISOString(),source:text(plan.source)||'import',notes:Array.isArray(plan.notes)?plan.notes.map(text).filter(Boolean):[],documentAssignments,loadCorrections};}
async function gunzip(bytes){if(typeof DecompressionStream==='undefined')throw new Error('This iPhone version cannot open compressed packages.');const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return new Uint8Array(await new Response(stream).arrayBuffer());}
function parseTar(bytes){const files=new Map();let offset=0;while(offset+512<=bytes.length){const header=bytes.slice(offset,offset+512);if(header.every(v=>v===0))break;const name=bytesToText(header.slice(0,100)).replace(/\0.*$/,'');const size=parseInt(bytesToText(header.slice(124,136)).replace(/\0.*$/,'').trim()||'0',8)||0;const start=offset+512;if(name)files.set(name,bytes.slice(start,start+size));offset=start+Math.ceil(size/512)*512;}return files;}
async function inflateRaw(bytes){if(typeof DecompressionStream==='undefined')throw new Error('ZIP decompression is not supported on this iPhone.');const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return new Uint8Array(await new Response(stream).arrayBuffer());}
async function parseZip(bytes){const files=new Map();const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let offset=0;while(offset+30<=bytes.length&&view.getUint32(offset,true)===0x04034b50){const method=view.getUint16(offset+8,true),compressed=view.getUint32(offset+18,true),nameLen=view.getUint16(offset+26,true),extraLen=view.getUint16(offset+28,true);const name=bytesToText(bytes.slice(offset+30,offset+30+nameLen));const start=offset+30+nameLen+extraLen;const packed=bytes.slice(start,start+compressed);if(!(name.endsWith('/'))){if(method===0)files.set(name,packed);else if(method===8)files.set(name,await inflateRaw(packed));else throw new Error(`Unsupported ZIP method ${method}.`);}offset=start+compressed;}return files;}
function packagePreview(files){const names=[...files.keys()];const repairName=names.find(n=>/(^|\/)repair[-_]?plan.*\.json$/i.test(n));const manifestName=names.find(n=>/(^|\/)import[-_]?manifest\.json$/i.test(n))||names.find(n=>/document[-_]?manifest\.json$/i.test(n));const plan=repairName?normalizePlan(safeJson(bytesToText(files.get(repairName)))):null;const rawManifest=manifestName?safeJson(bytesToText(files.get(manifestName))):null;const documents=Array.isArray(rawManifest)?rawManifest:(rawManifest?.documents||[]);return{kind:documents.length?'complete_package':'audit',fileCount:names.length,originalCount:names.filter(n=>/originals\/|documents\//i.test(n)).length,plan,manifest:rawManifest,documents,files,names};}
export async function inspectRepairImportV10975(file){const name=text(file?.name).toLowerCase();if(!file)throw new Error('Choose a file first.');const bytes=new Uint8Array(await file.arrayBuffer());if(name.endsWith('.json')){const parsed=safeJson(bytesToText(bytes));if(!parsed)throw new Error('JSON file could not be read.');return{kind:'repair',plan:normalizePlan(parsed),fileName:file.name};}let files;if(name.endsWith('.tar.gz')||name.endsWith('.tgz'))files=parseTar(await gunzip(bytes));else if(name.endsWith('.zip'))files=await parseZip(bytes);else throw new Error('Use a Road Ready .json, .zip or .tar.gz package.');return{...packagePreview(files),fileName:file.name};}
async function sha256(bytes){const digest=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('');}
function normalizeImportDoc(x={}){return{path:text(x.path||x.fileName||x.file_name),loadNo:upper(x.loadNo||x.load_no),documentType:text(x.documentType||x.document_type||x.type||'other').toLowerCase(),stopSequence:Number(x.stopSequence||x.stop_sequence||0)||0,documentDate:text(x.documentDate||x.document_date).slice(0,10),title:text(x.title),mimeType:text(x.mimeType||x.mime_type),sha256:text(x.sha256).toLowerCase()};}
export async function applyCompletePackageV10979(inspection){if(!inspection?.files||!inspection?.documents)throw new Error('Complete package data is missing.');if(inspection.plan)applyRepairPlanV10975(inspection.plan);const existing=await listVaultDocumentsV102();const existingHashes=new Set(existing.map(d=>text(d.sha256||d.content_hash||d.metadata?.sha256).toLowerCase()).filter(Boolean));const logical=new Set(existing.map(d=>`${upper(d.load_no||d.extracted?.loadNo)}|${text(d.type||d.extracted?.type).toLowerCase()}|${Number(d.stopSequence||d.extracted?.stopSequence||0)}`));let imported=0,duplicates=0,missing=0;for(const raw of inspection.documents){const doc=normalizeImportDoc(raw);const bytes=inspection.files.get(doc.path)||inspection.files.get(raw.fileName)||inspection.files.get(raw.file_name);if(!bytes){missing++;continue;}const hash=doc.sha256||await sha256(bytes);const key=`${doc.loadNo}|${doc.documentType}|${doc.stopSequence}`;if(existingHashes.has(hash)||(['rate_confirmation','pod'].includes(doc.documentType)&&logical.has(key))){duplicates++;continue;}const file=new File([bytes],doc.path.split('/').pop()||'document',{type:doc.mimeType||'application/octet-stream'});await saveScannedDocument({file,type:doc.documentType,title:doc.title||file.name,metadata:{loadNo:doc.loadNo,relationType:doc.documentType,logDate:doc.documentDate},extracted:{type:doc.documentType,loadNo:doc.loadNo,date:doc.documentDate,stopSequence:doc.stopSequence},classification:{selectedType:doc.documentType,confidence:1,source:'verified_cleanup_package'},});existingHashes.add(hash);logical.add(key);imported++;}window.dispatchEvent(new Event('road-ready-repair-applied'));return{imported,duplicates,missing};}
export function readRepairOverlayV10975(){if(typeof window==='undefined')return{documentAssignments:[],loadCorrections:[]};return safeJson(localStorage.getItem(KEY))||{documentAssignments:[],loadCorrections:[]};}
export function applyRepairPlanV10975(plan){if(typeof window==='undefined')throw new Error('Repair import only works in the app.');const normalized=normalizePlan(plan),previous=localStorage.getItem(KEY)||'';const history=safeJson(localStorage.getItem(HISTORY))||[];history.unshift({at:new Date().toISOString(),previous,plan:normalized});localStorage.setItem(HISTORY,JSON.stringify(history.slice(0,10)));const current=readRepairOverlayV10975();const docMap=new Map((current.documentAssignments||[]).map(x=>[x.documentId,x]));normalized.documentAssignments.forEach(x=>docMap.set(x.documentId,{...(docMap.get(x.documentId)||{}),...x}));const loadMap=new Map((current.loadCorrections||[]).map(x=>[x.loadNo||x.aliasFrom,x]));normalized.loadCorrections.forEach(x=>loadMap.set(x.loadNo||x.aliasFrom,{...(loadMap.get(x.loadNo||x.aliasFrom)||{}),...x}));const next={schema:'road_ready_repair_overlay_v1',updatedAt:new Date().toISOString(),documentAssignments:[...docMap.values()],loadCorrections:[...loadMap.values()]};localStorage.setItem(KEY,JSON.stringify(next));window.dispatchEvent(new CustomEvent('road-ready-repair-applied',{detail:{summary:{documents:normalized.documentAssignments.length,loads:normalized.loadCorrections.length}}}));return next;}
export function undoLastRepairV10975(){if(typeof window==='undefined')return false;const history=safeJson(localStorage.getItem(HISTORY))||[],last=history.shift();if(!last)return false;if(last.previous)localStorage.setItem(KEY,last.previous);else localStorage.removeItem(KEY);localStorage.setItem(HISTORY,JSON.stringify(history));window.dispatchEvent(new Event('road-ready-repair-applied'));return true;}
export function repairSummaryV10975(plan={}){const p=normalizePlan(plan);return{documents:p.documentAssignments.length,loads:p.loadCorrections.length,ignoredDocuments:p.documentAssignments.filter(x=>x.ignore).length,legacyLoads:p.loadCorrections.filter(x=>x.legacy).length,stopCorrections:p.loadCorrections.filter(x=>x.deliveryStops>0).length};}
