'use client';

import React,{useRef,useState} from 'react';
import {inspectRepairImportV10975,applyRepairPlanV10975,applyCompletePackageV10979,undoLastRepairV10975,repairSummaryV10975} from './repairImportV10975.js';
import './repairImportV10975.css';

export default function RepairImportPanelV10975({onApplied}){
  const inputRef=useRef(null);const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[inspection,setInspection]=useState(null);const[error,setError]=useState('');const[message,setMessage]=useState('');
  async function choose(event){const file=event.target.files?.[0];if(!file)return;setBusy(true);setError('');setMessage('Reading and checking package…');try{const result=await inspectRepairImportV10975(file);setInspection(result);setMessage('');}catch(e){setError(String(e?.message||e));setInspection(null);setMessage('');}finally{setBusy(false);event.target.value='';}}
  async function apply(){if(!inspection)return;setBusy(true);setError('');try{if(inspection.kind==='complete_package'){const result=await applyCompletePackageV10979(inspection);setMessage(`Cleanup complete: ${result.imported} documents imported, ${result.duplicates} duplicates skipped${result.missing?`, ${result.missing} package files missing`:''}. Originals were not overwritten.`);}else if(inspection.plan){const summary=repairSummaryV10975(inspection.plan);applyRepairPlanV10975(inspection.plan);setMessage(`Applied ${summary.documents} document fixes and ${summary.loads} load fixes. Originals were not changed.`);}setInspection(null);onApplied?.();}catch(e){setError(String(e?.message||e));}finally{setBusy(false);}}
  function undo(){if(undoLastRepairV10975()){setMessage('Last metadata repair was undone. Imported originals remain safely stored.');setInspection(null);onApplied?.();}else setMessage('No repair history is available.');}
  const summary=inspection?.plan?repairSummaryV10975(inspection.plan):null;const packageDocs=inspection?.documents?.length||0;
  return <><button type="button" className="repair-import-open-v10975" onClick={()=>setOpen(true)}>Import repair</button>{open?<div className="repair-import-backdrop-v10975" role="dialog" aria-modal="true"><section className="repair-import-sheet-v10975">
    <header><div><span>SAFE DATA REPAIR</span><h2>Clean and complete load folders</h2></div><button type="button" onClick={()=>setOpen(false)}>Close</button></header>
    <p className="repair-import-intro-v10975">Import one Road Ready cleanup ZIP, audit package or repair JSON. Every correction and document is previewed. Existing originals, PDFs, photos and Logbook events are never overwritten.</p>
    <input ref={inputRef} hidden type="file" accept=".json,.zip,.tar.gz,.tgz,application/json,application/zip,application/gzip" onChange={choose}/>
    <div className="repair-import-actions-v10975"><button type="button" className="primary" disabled={busy} onClick={()=>inputRef.current?.click()}>{busy?'Working…':'Choose cleanup / repair file'}</button><button type="button" disabled={busy} onClick={undo}>Undo last repair</button></div>
    {error?<div className="repair-import-error-v10975">{error}</div>:null}{message?<div className="repair-import-message-v10975">{message}</div>:null}
    {inspection?.kind==='audit'&&!inspection.plan?<div className="repair-import-audit-v10975"><b>Audit package opened safely</b><span>{inspection.fileCount} package files · {inspection.originalCount} originals detected</span><p>This audit has no approved repair plan. Nothing was changed.</p></div>:null}
    {inspection?.kind==='complete_package'?<div className="repair-import-preview-v10975"><div className="repair-import-preview-title-v10975"><div><span>COMPLETE PACKAGE PREVIEW</span><b>{inspection.fileName}</b></div><i>✓</i></div><div className="repair-import-stats-v10975"><div><b>{packageDocs}</b><span>Verified documents</span></div><div><b>{summary?.loads||0}</b><span>Load corrections</span></div><div><b>{summary?.stopCorrections||0}</b><span>Stop corrections</span></div><div><b>SHA</b><span>Duplicate protection</span></div></div><div className="repair-import-notes-v10975"><p>Identical SHA-256 files are skipped. Rate Cons and PODs already linked to the same load/stop are not duplicated. Supporting packets never count as BOL or POD.</p></div><div className="repair-import-change-list-v10975">{inspection.documents.slice(0,20).map((item,index)=><article key={index}><i>D</i><div><b>{item.title||item.fileName||item.path}</b><span>Load {item.loadNo||item.load_no||'Review'} · {item.documentType||item.document_type||'other'}{Number(item.stopSequence||item.stop_sequence)>0?` · Stop ${item.stopSequence||item.stop_sequence}`:''}</span></div></article>)}</div><div className="repair-import-confirm-v10975"><p><b>Safe cleanup.</b> Existing originals stay immutable; only verified missing files are added.</p><button type="button" disabled={busy} onClick={apply}>{busy?'Importing…':'Apply cleanup package'}</button></div></div>:null}
    {inspection?.kind!=='complete_package'&&summary?<div className="repair-import-preview-v10975"><div className="repair-import-preview-title-v10975"><div><span>PREVIEW ONLY</span><b>{inspection.fileName||'Repair plan'}</b></div><i>✓</i></div><div className="repair-import-stats-v10975"><div><b>{summary.documents}</b><span>Document links</span></div><div><b>{summary.loads}</b><span>Load corrections</span></div><div><b>{summary.stopCorrections}</b><span>Stop counts</span></div><div><b>{summary.legacyLoads}</b><span>Legacy loads</span></div></div>{inspection.plan.notes?.length?<div className="repair-import-notes-v10975">{inspection.plan.notes.map((note,index)=><p key={index}>{note}</p>)}</div>:null}<div className="repair-import-confirm-v10975"><p><b>No destructive changes.</b> A rollback snapshot is saved before applying.</p><button type="button" disabled={busy} onClick={apply}>Apply reviewed repair</button></div></div>:null}
  </section></div>:null}</>;
}
