import fs from 'node:fs';
import { spawnSync } from 'node:child_process';
const path='scripts/build-v109718.mjs';
const original=fs.readFileSync(path,'utf8');
const anchor="run('npx',['next','build']);";
if(original.split(anchor).length!==2)throw new Error('Legacy build anchor changed; refusing an ambiguous build');
const steps=['apply-v110-cloud.mjs','test-owner-op-cloud-v110.mjs','verify-owner-op-cloud-service.mjs','apply-module-isolation-v110.mjs','finalize-signature-persistence-v110.mjs','finalize-signature-ui-v110.mjs','apply-logbook-editor-v110.mjs','finalize-logbook-editor-v110.mjs','apply-compact-editor-v111.mjs','finalize-compact-contrast-v111.mjs','finalize-migration-guard-v1102.mjs','apply-motive-override-v11023.mjs','finalize-quick-chip-accessibility-v11023.mjs','finalize-live-continuity-v11024.mjs','test-migration-guard-v1102.mjs','test-logbook-editor-v110.mjs','test-logbook-followup-v11021.mjs','test-compact-editor-v111.mjs','test-motive-override-v11023.mjs','test-live-continuity-v11024.mjs','finalize-midnight-carry-v11025.mjs','test-midnight-carry-v11025.mjs','finalize-canonical-continuity-v11026b.mjs','test-canonical-continuity-v11026.mjs','finalize-modern-editor-v11027.mjs','finalize-browser-edit-reveal-v11027.mjs','test-modern-editor-v11027.mjs','finalize-wizard-next-toast-v11027.mjs','test-wizard-next-toast-v11027.mjs','finalize-dot-officer-email-v11028.mjs','finalize-dot-officer-email-privacy-v11028.mjs','finalize-dot-officer-eight-day-guard-v11028.mjs','finalize-legacy-browser-layout-v11028.mjs','finalize-live-note-browser-v11028.mjs','test-dot-officer-email-v11028.mjs','finalize-ratecon-one-way-v11029.mjs','test-ratecon-one-way-v11029.mjs','finalize-live-start-edit-v110210.mjs','test-live-start-edit-v110210.mjs','test-module-isolation-v110.mjs','test-day-form-v110.mjs','finalize-duty-graph-continuity-v110212.mjs','test-duty-graph-continuity.mjs','test-rendered-duty-graph.mjs','verify-isolation-locks-v110.mjs'];
steps.push('finalize-live-archive-v1103.mjs','test-live-archive-evidence.mjs','test-live-archive-runtime.mjs','finalize-parts-receipt-reader-v11031c.mjs','finalize-parts-receipt-release-tests-v11031.mjs','test-parts-receipt-reader-v11031.mjs','verify-isolation-locks-v110.mjs');
steps.push('finalize-status-midnight-carry-v11032.mjs','test-status-midnight-carry-v11032.mjs','test-duty-graph-continuity.mjs','verify-isolation-locks-v110.mjs');
steps.push('finalize-smart-load-identity-v11033.mjs','test-smart-load-identity-v11033.mjs','verify-isolation-locks-v110.mjs');
steps.push('finalize-live-load-scanner-editor-v11034c.mjs','test-live-load-scanner-editor-v11034.mjs','verify-isolation-locks-v110.mjs');
steps.push('finalize-live-bol-context-v11035c.mjs','test-live-bol-context-v11035c.mjs','verify-isolation-locks-v110.mjs');
steps.push('finalize-smart-scanner-v11036.mjs','test-smart-scanner-v11036.mjs','verify-isolation-locks-v110.mjs');
steps.push('finalize-scanner-load-link-v11037.mjs','test-scanner-load-link-v11037.mjs','verify-isolation-locks-v110.mjs');
const program=original.replace(anchor,steps.map(script=>`run(process.execPath,['scripts/${script}']);`).join('\n')+'\n'+anchor);
fs.mkdirSync('.release',{recursive:true});fs.writeFileSync('.release/build-v110.generated.mjs',program);
const result=spawnSync(process.execPath,['.release/build-v110.generated.mjs'],{stdio:'inherit'});
if(result.error)throw result.error;process.exit(result.status??1);
