import assert from 'node:assert/strict';
import fs from 'node:fs';
import {addTeamDriver,switchTeamDriver,sealActiveDriverLogbook,importedLogbookIntegrity,DRIVER_MILEAGE_FIELDS} from '../../source/src/core/team/teamLogbook.js';
import {routeLegsForDayCanonical,normalizeLoadInfoFromRouteLegs} from '../../source/src/core/routes/routeNormalization.js';
import {routeHistoryIndex,routeHistoryWindow,freightOriginForLeg} from '../../source/src/core/routes/shipmentCarryover.js';
import {buildFullBackupPayloadV105} from '../../source/src/modules/backup/fullBackupV105.js';
const pickupDay='2026-09-27',driveDay='2026-09-28',deliveryDay='2026-09-29',after='2026-09-30';
const pickup={id:'beta-pickup',status:'ON',startMin:500,endMin:540,city:'Philadelphia',state:'PA',note:'Pickup / Loading',shippingDocs:'BOL-TEST',source:'manual'};
const delivery={id:'alpha-delivery',status:'ON',startMin:500,endMin:530,city:'Chicago',state:'IL',note:'Delivery / Unloading',shippingDocs:'BOL-TEST',source:'manual'};
const route={id:'freight-1',day:pickupDay,pickupDay,pickupEventId:pickup.id,pickupMin:500,kind:'loaded',status:'open',shippingDocs:'BOL-TEST',fromCity:'Columbus',fromState:'OH',toCity:'Chicago',toState:'IL',miles:700};
let team=addTeamDriver({activeDay:driveDay,driverProfile:{name:'Alpha'},eventsByDay:{[driveDay]:[{id:'alpha-drive',status:'D',startMin:600,endMin:900,city:'Columbus',state:'OH',manualMiles:300}], [deliveryDay]:[delivery]},manualMilesByDay:{[driveDay]:300},signatureByDay:{},routeLegsByDay:{[pickupDay]:[route]},loadInfo:{loadNo:'BOL-TEST',shippingDocs:'BOL-TEST',sourceEventId:pickup.id,sourceEventDay:pickupDay}},'Beta',driveDay);
const alpha=team.activeDriverId,beta=team.teamDrivers[1].id;
let second=switchTeamDriver(team,beta,driveDay);
assert.deepEqual(second.manualMilesByDay,{},'new driver must not inherit day miles');
second={...second,eventsByDay:{[pickupDay]:[pickup],[driveDay]:[{id:'beta-drive',status:'D',startMin:100,endMin:400,city:'Philadelphia',state:'PA',manualMiles:225}]},manualMilesByDay:{[driveDay]:225}};
team=switchTeamDriver(second,alpha,driveDay);
const raw=structuredClone(team),roundTrip=switchTeamDriver(JSON.parse(JSON.stringify(switchTeamDriver(team,beta,driveDay))),alpha,driveDay);
assert.equal(roundTrip.manualMilesByDay[driveDay],300);
assert.equal(switchTeamDriver(roundTrip,beta,driveDay).manualMilesByDay[driveDay],225);
assert.deepEqual(roundTrip.eventsByDay,raw.eventsByDay);
assert.deepEqual(roundTrip.routeLegsByDay,raw.routeLegsByDay);
console.log('PASS — separate mileage survives switch, reload and repeated switch');
for(const field of DRIVER_MILEAGE_FIELDS){const s=addTeamDriver({activeDay:driveDay,driverProfile:{name:'A'},[field]:{[driveDay]:77}},'B',driveDay);const b=s.teamDrivers[1].id;assert.deepEqual(switchTeamDriver(s,b,driveDay)[field],{});assert.deepEqual(switchTeamDriver(switchTeamDriver(s,b,driveDay),s.activeDriverId,driveDay)[field],{[driveDay]:77});}
console.log('PASS — all legacy mileage formats stay with their driver');
for(const id of [alpha,beta]){const s=switchTeamDriver(team,id,driveDay);for(const day of [pickupDay,driveDay,deliveryDay])assert.deepEqual(routeLegsForDayCanonical(s,day).map(l=>l.id),['freight-1']);assert.deepEqual(routeLegsForDayCanonical(s,after),[]);const index=routeHistoryIndex(s),window=routeHistoryWindow(route,index);assert.equal(window.endDay,deliveryDay);assert.equal(window.endReason,'delivery');assert.deepEqual(freightOriginForLeg(s,route,index),{city:'Philadelphia',state:'PA'});assert.equal(normalizeLoadInfoFromRouteLegs(s).loadInfo.pickupCity,'Philadelphia');}
console.log('PASS — both drivers see freight pickup through delivery, with Philadelphia origin');
const unlinked={...team,eventsByDay:{[driveDay]:raw.eventsByDay[driveDay],[deliveryDay]:[{...delivery,id:'unlinked-delivery'}]}};
assert.deepEqual(routeLegsForDayCanonical(unlinked,after),[]);
console.log('PASS — matching unlinked delivery by the other driver closes the freight window');
const conflict={...team,eventsByDay:{[deliveryDay]:[{...delivery,shippingDocs:'OTHER-BOL'}]}};
assert.equal(routeLegsForDayCanonical(conflict,after).length,1);
console.log('PASS — another load delivery cannot close this freight');
const sealed=sealActiveDriverLogbook(team),payload=buildFullBackupPayloadV105(sealed,{},{});
assert.equal(importedLogbookIntegrity(sealed,payload.state).ok,true);
assert.equal(payload.state.manualMilesByDay[driveDay],300);
assert.equal(payload.state.teamLogbooksByDriverId[beta].manualMilesByDay[driveDay],225);
const broken=structuredClone(payload.state);broken.teamLogbooksByDriverId[beta].manualMilesByDay[driveDay]=300;
assert.equal(importedLogbookIntegrity(sealed,broken).ok,false);
console.log('PASS — full backup preserves and validates each driver mileage');
assert.deepEqual(team,raw,'freight projections must not change saved records');
assert.equal(routeLegsForDayCanonical(team,driveDay)[0].fromCity,'Philadelphia');
console.log('7 team mileage and freight regression groups passed');
