'use client';
import React,{useEffect,useState} from 'react';
import {syncRecords,recordSyncStatus,SYNC_EVENT,listRecords,listCorrections,applyCorrection,recordSyncPaused,pauseRecordSync} from '../../../../lib/owner-op-cloud/recordSyncV110451.js';
import {pauseMirror} from '../../../../lib/owner-op-cloud/cloudMirrorV110450.js';
const kinds=[['business_loads','Loads'],['documents','Original document records'],['logbook_days','Logbook days'],['duty_events','Duty events'],['routes','Routes'],['drivers','Drivers'],['wallet','Wallet'],['signatures','Signatures'],['inspections','Inspections'],['forms','Daily forms'],['business_expenses','Expenses'],['business_fuel','Fuel'],['business_maintenance','Maintenance'],['settings','Settings'],['recovery_history','Saved history']];
const label=key=>key.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ').replace(/^./,s=>s.toUpperCase());
const display=value=>value===null||value===undefined?'Not set':typeof value==='object'?JSON.stringify(value):String(value);
export default function RecordSyncPanel(){
 const [status,setStatus]=useState(recordSyncStatus),[kind,setKind]=useState('business_loads'),[search,setSearch]=useState(''),[rows,setRows]=useState([]),[changes,setChanges]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[paused,setPaused]=useState(false);
 const refresh=async()=>{const [records,corrections]=await Promise.all([listRecords(kind,search),listCorrections()]);setRows(records||[]);setChanges(corrections||[]);};
 useEffect(()=>{setPaused(recordSyncPaused());const update=e=>setStatus(e.detail);window.addEventListener(SYNC_EVENT,update);syncRecords().then(refresh).catch(e=>setMessage(e.message));return()=>window.removeEventListener(SYNC_EVENT,update);},[]);
 async function act(fn){setBusy(true);setMessage('');try{const result=await fn();if(result?.error)throw Error(result.error);if(result?.message)setMessage(result.message);await refresh();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const pending=changes.filter(c=>c.status==='pending');
 return <section className="rr-card" aria-label="Synchronized records"><span className="rr-eyebrow">RECORDS &amp; CORRECTIONS</span><h2>Saved records, easy to check</h2><p>See this device’s saved loads, files and driver records. Every change keeps its earlier version.</p><p role="status">{status.message}</p>{status.completedAt?<p>Last sync: {new Date(status.completedAt).toLocaleString()}</p>:null}<div className="rr-actions"><button disabled={busy||status.phase==='running'||paused} onClick={()=>act(()=>syncRecords({force:true}))}>Sync records now</button><button disabled={busy} onClick={()=>{const next=!paused;pauseRecordSync(next);pauseMirror(next);setPaused(next);if(!next)act(()=>syncRecords({force:true}));}}>{paused?'Resume cloud work':'Pause cloud work on this device'}</button></div>
 <p>Local records and existing backups stay available when paused.</p>
 {pending.length?<div><h3>Corrections to review ({pending.length})</h3>{pending.map(change=><article key={change.id} style={{padding:'14px 0',borderTop:'1px solid #dbe3ed'}}><b>{change.reason}</b><p>{kinds.find(([key])=>key===change.kind)?.[1]||label(change.kind)}</p><dl>{[...Object.keys(change.patch),...(change.unset||[])].map(field=><div key={field}><dt>{label(field)}</dt><dd style={{marginLeft:0,overflowWrap:'anywhere'}}>{display(change.before_data[field])} → {display(change.patch[field])}</dd></div>)}</dl><button disabled={busy||paused} onClick={()=>act(async()=>{const result=await applyCorrection(change);if(result.status==='applied')await syncRecords({force:true});return result;})}>Apply correction</button></article>)}</div>:null}
 {message?<p role="status" style={{overflowWrap:'anywhere'}}>{message}</p>:null}
 <details><summary>Browse saved records</summary><form onSubmit={e=>{e.preventDefault();act(async()=>{});}} style={{display:'grid',gap:10,marginTop:12}}><label>Record type<select value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label>Find a load<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Load number"/></label><button disabled={busy}>Search records</button></form><p>Showing up to 60 records for this device.</p>{rows.map(row=><details key={row.record_key} style={{padding:'12px 0',borderBottom:'1px solid #e1e7ef'}}><summary>{row.load_no?'Load '+row.load_no:row.data?.original_file_name||row.data?.originalFileName||row.data?.name||row.day||label(row.kind)}{row.day?' · '+row.day:''}</summary>{row.locator?.duplicate?<p>Multiple saved records share this ID. Each copy is preserved for review.</p>:null}<p>Revision {row.revision} · Saved {new Date(row.captured_at).toLocaleString()}{row.origin==='backup_review'?' · From verified backup':''}</p><dl>{Object.entries(row.data&&typeof row.data==='object'?row.data:{value:row.data}).map(([key,value])=><div key={key}><dt>{label(key)}</dt><dd style={{marginLeft:0,whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:180,overflow:'auto'}}>{display(value)}</dd></div>)}</dl></details>)}</details>
 {changes.some(c=>c.status!=='pending')?<details><summary>Recent correction results</summary>{changes.filter(c=>c.status!=='pending').slice(0,10).map(c=><p key={c.id}><b>{label(c.status)}</b> · {c.reason}<br/>{c.result?.message}</p>)}</details>:null}
 </section>;
}
