import assert from 'node:assert/strict';
import {projectRecords,visible,allowedFields,prepareCorrection,canonical} from './recordsCore.js';
const day='2026-09-30',event={id:'same-event',loadNo:'803',status:'ON',startMin:1057,endMin:1072};
const state={activeDriverId:'arben',teamDrivers:[{id:'arben',name:'Arben'},{id:'feriz',name:'Feriz'}],eventsByDay:{[day]:[event]},signatureByDay:{[day]:{signature:'data:image/png;base64,AAAA'}},teamLogbooksByDriverId:{arben:{eventsByDay:{[day]:[{...event,status:'STALE'}]}},feriz:{eventsByDay:{[day]:[{...event,id:'same-event',status:'OFF'}]}}},routeLegsByDay:{[day]:[{id:'leg',loadNo:'803',toCity:'East Haven'}]},dotWallet:{documents:{insurance:{title:'Insurance',dataUrl:'data:application/pdf;base64,AA=='}}}};
const original=new Blob(['original bytes'],{type:'application/pdf'}),business={loads:[{id:'one',loadNo:'803',broker:'Unknown',unknown:{preserve:true}}]};
const bundle={state,business,tables:{documents_local:[{id:'server-id',local_id:'doc',title:'BOL',blob:original}],document_blobs:[{local_blob_id:'blob',blob:original}],sync_meta:[{key:'owner-op-record-sync-v1:cache',value:{secret:'excluded'}}]},localRows:[{key:'owner-op-test',value:'{"password":"hidden","valid":true}'},{key:'auth-session',value:'secret'}]};
const rows=projectRecords(bundle),find=key=>rows.find(r=>r.record_key===key);
assert.equal(rows.filter(r=>r.kind==='duty_events').length,2);
assert.equal(find('event/arben/'+day+'/same-event').data.status,'ON');
assert.equal(find('event/feriz/'+day+'/same-event').data.status,'OFF');
assert.equal(find('db/documents_local/doc').locator.id,'doc');
assert.equal(find('db/document_blobs/blob').data.blob.fileBytes,14);
assert.equal(find('wallet/insurance').data.dataUrl.originalInBackup,true);
assert(!canonical(rows).includes('hidden'));assert(!canonical(rows).includes('AAAA'));assert(!canonical(rows).includes('excluded'));
assert.deepEqual(visible({refresh_token:'hidden',nested:{access_token:'hidden',fine:1}}),{nested:{fine:1}});
const record=find('business/loads/one'),change={before_data:record.data,patch:{broker:'Verified broker'},unset:[]};
const planned=prepareCorrection(bundle,record,change);assert.equal(planned.next.broker,'Verified broker');assert.deepEqual(planned.next.unknown,{preserve:true});assert.equal(business.loads[0].broker,'Unknown');
assert(prepareCorrection({...bundle,business:{loads:[planned.next]}},record,change).alreadyApplied);
assert.throws(()=>prepareCorrection({...bundle,business:{loads:[{...business.loads[0],notes:'new phone edit'}]}},record,change),/Conflict/);
const document=find('db/documents_local/doc'),docPlan=prepareCorrection(bundle,document,{before_data:document.data,patch:{title:'Correct BOL'}});assert.equal(docPlan.next.blob,original);
assert.throws(()=>prepareCorrection(bundle,record,{...change,patch:{id:'two'}}),/original app workflow/);
assert.throws(()=>prepareCorrection(bundle,find('event/arben/'+day+'/same-event'),{before_data:event,patch:{startMin:0}}),/original app workflow/);
assert.throws(()=>prepareCorrection(bundle,find('signatures/arben/'+day),{patch:{signature:'changed'}}),/original app workflow/);
const fragments=projectRecords({state:{},business:{loads:[{id:'large',notes:'x'.repeat(900000)}]}}).filter(r=>r.record_key.startsWith('business/loads/large'));
assert(fragments.length>3);assert(fragments.every(r=>r.locator.fragment&&allowedFields(r).length===0));
const duplicateBundle={business:{loads:[{id:'load_424590-1',loadNo:'424590-1',broker:'Red Lightning',gross:2700},{id:'load_424590-1',loadNo:'424590-1',broker:'Select Transport',gross:1000},{id:'load_424590-1',loadNo:'424590-1',broker:'Third retained copy',gross:1000}]}},saved=canonical(duplicateBundle);
const duplicates=projectRecords(duplicateBundle).filter(r=>r.kind==='business_loads');
assert.equal(duplicates.length,3);assert.equal(new Set(duplicates.map(r=>r.record_key)).size,3);assert(duplicates.every(r=>r.locator.duplicate&&allowedFields(r).length===0));assert.deepEqual(duplicates.map(r=>r.data.gross),[2700,1000,1000]);assert.equal(canonical(duplicateBundle),saved);assert.equal(canonical(projectRecords(duplicateBundle)),canonical(projectRecords(duplicateBundle)));
const staleRecord={...duplicates[0],locator:{...duplicates[0].locator,duplicate:false}};
assert.throws(()=>prepareCorrection(duplicateBundle,staleRecord,{before_data:duplicates[0].data,patch:{broker:'Do not overwrite both'}}),/Conflict: multiple/);
const collision=projectRecords({business:{loads:[{id:'same'},{id:'same'},{id:'same/duplicate/2'}]}});assert.equal(new Set(collision.map(r=>r.record_key)).size,collision.length);
assert.equal(canonical({z:1,a:2}),canonical({a:2,z:1}));
console.log('PASS records: driver isolation, active source, file/credential redaction, large records, exact conflicts, idempotence, protected fields and original preservation');
