import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleSource=fs.readFileSync(new URL('./driverDocuments.js',import.meta.url),'utf8').replace('./evidenceCoreV110413.js',new URL('../v110413/evidenceCore.js',import.meta.url).href).replace('./documentBrowserV110404.js',new URL('../v110404/documentBrowser.js',import.meta.url).href);
const {shortPlace,loadView,loadReviewRows}=await import('data:text/javascript;base64,'+Buffer.from(moduleSource).toString('base64'));
const hash='a'.repeat(64),load={loadNo:'TEST10',origin:'12 Test Road, Alpha, IL',destination:'18 Test Ave, Beta, IN',status:'delivered',pickupDate:'2026-09-24',deliveryDate:'2026-09-25'};
const fields={date:'2026-09-25',loadNo:'TEST10',merchant:'Test Broker',origin:load.origin,destination:load.destination,pickupDate:'2026-09-24',deliveryDate:'2026-09-25',total:500,currency:'USD',reference:'TEST',podSigned:true};
const packet={client_document_id:'packet',load_no:'TEST10',type:'supporting_packet',sha256:hash,extracted:{evidenceFactsV1:{version:1,sourceSha256:hash,reviewedAt:'2026-09-25',fields,components:['invoice','rate_confirmation','bol','pod'].map((kind,i)=>({kind,fields,reviewed:true,pages:[i+1]}))}}};
const business={loads:[{...load,documentWorkflowStage:'delivered',gross:500}]};
const before=JSON.stringify({load,packet,business});
const complete=loadView(load,[packet],business,'2026-09-27');
assert.equal(complete.origin,'Alpha, IL');assert.equal(complete.destination,'Beta, IN');assert.equal(complete.amount,500);
assert.equal(complete.rows.length,4);assert.equal(complete.onFile,4);assert.equal(complete.files.length,1);assert.equal(complete.attention,0,'global mileage/fuel coverage is not a load alert');
assert.equal(complete.rows.find(r=>r.kind==='rate_confirmation').sources[0].pages[0],2);
assert.deepEqual(complete.rows.find(r=>r.kind==='bol').sources[0].pages,[3],'pickup opens the BOL pages, not the POD pages');
assert.deepEqual(complete.rows.find(r=>r.kind==='pod').sources[0].pages,[4]);
assert.match(complete.service,/Delivered Sep 25/);assert.equal(JSON.stringify({load,packet,business}),before);
const incomplete={...packet,extracted:{...packet.extracted,evidenceFactsV1:{...packet.extracted.evidenceFactsV1,reviewedAt:null}}};
assert.ok(loadView(load,[incomplete],business).attention>0);assert.equal(loadView(load,[incomplete],business).rows[0].status,'review');
const chosen=loadView(load,[incomplete,{...packet,client_document_id:'reviewed'}],business);
assert.equal(chosen.rows[0].sources[0].doc.client_document_id,'reviewed','a reviewed source opens first');
assert.equal(chosen.files.length,2,'different saved originals remain accessible');
const cross=structuredClone(packet);cross.extracted.evidenceFactsV1.components.find(c=>c.kind==='invoice').fields={...fields,loadNo:'OTHER'};
assert.equal(loadView(load,[cross],business).rows.find(r=>r.kind==='invoice').sources.length,0,'packet pages for another load never open under this load');
const future={...load,documentWorkflowStage:'picked_up',deliveryDate:'2026-09-28'};
assert.equal(loadView(future,[],{loads:[future]},'2026-09-27').rows.find(r=>r.kind==='pod').status,'not_due');
const tonu=loadView({...load,status:'complete'},[],{loads:[{...load,documentWorkflowStage:'tonu'}]});
assert.deepEqual(tonu.rows.map(r=>r.kind),['rate_confirmation','invoice']);assert.equal(tonu.status.label,'Cancelled · TONU');
assert.equal(shortPlace('Unknown location'),'Unknown location');assert.equal(shortPlace('99 Road, Alpha, IL 60000'),'Alpha, IL');
assert.equal(loadReviewRows({checks:[],issues:[{status:'review',action:'mileage'},{status:'review',document:{load_no:'OTHER'}}]},load).length,0);
console.log('PASS — compact load scope, truthful review status, packet page mapping, all originals, TONU, future delivery and unchanged data');
