import assert from 'node:assert/strict';
import {validateWalletImport,mergeWalletImport,walletFingerprint} from '../../source/src/modules/wallet/walletImportV110443.js';
import {derivedExpiresOn,requirementById} from '../../source/src/core/wallet/dotWallet.js';
const bytes=new TextEncoder().encode('%PDF-1.4\nSynthetic wallet original'),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');
const payload={format:'road-ready-wallet-documents',version:1,identity:{driverName:'Test Driver',unit:'TEST'},documents:[{id:'insurance_card',fields:{policyNo:'SYNTHETIC',expiresOn:'2027-09-22'},original:{base64:btoa(String.fromCharCode(...bytes)),sha256:hash,type:'application/pdf',size:bytes.length,name:'test.pdf'}}]};
const review=await validateWalletImport(payload),old={settings:{includeTrailerDocs:false},documents:{insurance_card:{present:true,attachmentDataUrl:'data:application/pdf;base64,T0xE',notes:'Keep old source'},ifta_license:{present:true,notes:'Keep unrelated'}}};
const before=structuredClone(old),next=mergeWalletImport(old,review,walletFingerprint(old),'token');assert.deepEqual(old,before);assert.deepEqual(next.documents.ifta_license,old.documents.ifta_license);assert.equal(next.settings.includeTrailerDocs,false);assert.equal(next.documents.insurance_card.previousVersions[0].notes,'Keep old source');assert.equal(next.lastImport.token,'token');
const again=mergeWalletImport(next,review,walletFingerprint(next),'again');assert.equal(again.documents.insurance_card.previousVersions.length,1,'repeat does not duplicate originals');
assert.throws(()=>mergeWalletImport({...old,lastReviewedAt:1},review,walletFingerprint(old),'stale'),/changed/);
for(const mutate of [p=>p.documents[0].original.sha256='0'.repeat(64),p=>p.documents[0].fields.expiresOn='2026-02-30',p=>p.documents[0].fields.signatureByDay='forbidden',p=>p.documents.push(p.documents[0]),p=>p.documents[0].id='unknown',p=>p.documents[0].original.type='text/html']){const p=structuredClone(payload);mutate(p);await assert.rejects(()=>validateWalletImport(p));}
assert.equal(derivedExpiresOn(requirementById('trailer_registration'),{expiresMonth:'2030-03'}),'2030-03-31');assert.equal(derivedExpiresOn(requirementById('trailer_registration'),{expiresMonth:'2028-02'}),'2028-02-29');
console.log('PASS — source bytes, invalid dates/types/fields, duplicates, stale preview, kept originals, repeated import, untouched settings/documents and month precision');
